// ── Progress keys of renamed or merged words ─────────────────
// Progress is keyed "<category>:<headword>" (engine/progress keyOf), so a
// corrected headword starts from zero and the old key lingers unused. Each
// pair maps the old key to the word it became; migrateKeys() in
// engine/progress moves saved progress across on load and on every sync
// merge, so a device or backup that still has the old key is carried
// over too. Several old keys may point at one new word (die Schuhe and
// der Schuh were two cards for one noun); their progress is merged.
export const RENAMED_KEYS = [
  ["nouns:Ivrith", "nouns:Hebräisch"],
  ["nouns:das Omelette", "nouns:das Omelett"],
  ["nouns:der Hip Hop", "nouns:der Hip-Hop"],
  ["nouns:der/das Comic", "nouns:der Comic"],
  ["nouns:die To-Do-Liste", "nouns:die To-do-Liste"],
  ["nouns:die Goldene Hochzeit", "nouns:die goldene Hochzeit"],
  ["nouns:die Salsa", "nouns:der Salsa"],
  ["nouns:die Bonbons", "nouns:das Bonbon"],
  ["nouns:die Zwillinge", "nouns:der Zwilling"],
  ["nouns:die Handschuhe", "nouns:der Handschuh"],
  ["nouns:die Sandalen", "nouns:die Sandale"],
  ["nouns:das Soziale Netzwerk", "nouns:das soziale Netzwerk"],
  ["nouns:die Pilgerschaft", "nouns:die Pilgerfahrt"],
  ["adj:soweit", "adj:so weit"],
  ["adj:bitteschön", "adj:bitte schön"],
  ["other:wohin", "other:wohin?"],
  ["phrases:ins Fitness-Studio gehen", "phrases:ins Fitnessstudio gehen"],
  ["chunks:Es hat sich etwas dazwischengeschoben.", "chunks:Mir ist etwas dazwischengekommen."],
  ["chunks:Am Ball bleiben", "chunks:am Ball bleiben"],
  ["chunks:Auf der Leitung stehen", "chunks:auf der Leitung stehen"],
  ["chunks:Den Nagel auf den Kopf treffen", "chunks:den Nagel auf den Kopf treffen"],
  ["chunks:Ein Brett vor dem Kopf haben", "chunks:ein Brett vor dem Kopf haben"],
  ["chunks:Seinen Senf dazugeben", "chunks:seinen Senf dazugeben"],
  ["chunks:Einen Kater haben", "chunks:einen Kater haben"],
  ["chunks:Die Katze im Sack kaufen", "chunks:die Katze im Sack kaufen"],
  ["chunks:Durch die Blume sagen", "chunks:etwas durch die Blume sagen"],
  ["chunks:Blaumachen", "chunks:blaumachen"],
  ["chunks:Etwas unter den Teppich kehren", "chunks:etwas unter den Teppich kehren"],
  ["chunks:Jemanden auf den Arm nehmen", "chunks:jemanden auf den Arm nehmen"],
  ["chunks:Die Nase voll haben von", "chunks:die Nase voll haben von"],
  ["nouns:die Disko", "nouns:die Disco"],
  ["nouns:der/das Blog", "nouns:der Blog"],
  ["nouns:der/das Laptop", "nouns:der Laptop"],
  ["nouns:die Kenntnisse", "nouns:die Kenntnis"],
  ["nouns:die Mahlzeiten", "nouns:die Mahlzeit"],
  ["nouns:das Fitness-Studio", "nouns:das Fitnessstudio"],
  ["nouns:die Schuhe", "nouns:der Schuh"],
  ["nouns:die Socken", "nouns:die Socke"],
  ["nouns:die Turnschuhe", "nouns:der Turnschuh"],
  ["nouns:die Nachrichten", "nouns:die Nachricht"],
  ["nouns:die Möbel", "nouns:das Möbel"],
  ["nouns:die Nudeln", "nouns:die Nudel"],
  ["other:zuletzt (zul.)", "other:zuletzt"],
  ["other:wann", "other:wann?"],
  ["other:warum", "other:warum?"],
  ["other:was", "other:was?"],
  ["other:wie", "other:wie?"],
  ["other:wo", "other:wo?"],
  ["other:woher", "other:woher?"],
  ["other:entweder … oder", "gram:entweder ... oder"],
  ["other:weder … noch", "gram:weder ... noch"],
  ["phrases:Wie geht es dir? (Wie geht’s?)", "phrases:Wie geht es dir?"],
  ["phrases:Wie geht’s dir?", "phrases:Wie geht es dir?"],
  ["phrases:Tschüs!", "phrases:Tschüss!"],
];
