// ── Kasus-Drill: decline article + adjective + noun ───────────
// Pick any slice of the combination space — case × gender/number ×
// determiner × with/without adjective × bare / after a preposition — and
// drill it. The questions are generated by engine/kasus, so there is no
// fixed list to run out of and every answer comes from the tables.
import { useState, useEffect, useMemo, useCallback, useRef } from "react";
import { COLORS, TXT, MUTE, FAINT } from "../config/theme";
import { lvlOf } from "../config/levels";
import { keyOf, applyAnswer, saveProgress } from "../engine/progress";
import {
  CASES, CASE_LABEL, CASE_SHORT, SLOTS, SLOT_LABEL, SLOT_SHORT, DETS, DET_LABEL,
  KASUS_CAT_ID, cellId, cellsFor, buildQuestion, drillNoun, normalize,
} from "../engine/kasus";
import { SpeakBtn, isTypingTarget } from "./ui";
import { ChipRow, weakFirst, ROUND, DRILL_ACCENT } from "./drillKit";

const ART_NOM = { m: "der", f: "die", n: "das", pl: "die" };
const GENDER_COLOR = { m: COLORS.der, f: COLORS.die, n: COLORS.das, pl: COLORS.plural };

const CONTEXTS = [
  { value: "plain", label: "Fall genannt" },
  { value: "prep", label: "Präposition" },
  { value: "twoway", label: "Wo? / Wohin?" },
];

// Filters survive a tab switch (the view unmounts), not a reload.
let saved = null;
let filtersOpen = false;
const DEFAULTS = {
  cases: [...CASES], slots: [...SLOTS], dets: ["def", "ein", "kein"], adj: ["adj", "-"],
  contexts: ["plain"], mode: "mc",
};

const contextFits = (ctx, kase) => ctx === "plain" || (ctx === "prep" && kase !== "nom") || (ctx === "twoway" && (kase === "akk" || kase === "dat"));

export function KasusDrill({ db, progress, setProgress, recordAnswer, levelFilter }) {
  const [f, setF] = useState(saved || DEFAULTS);
  const set = (patch) => setF((prev) => { const n = { ...prev, ...patch }; saved = n; return n; });

  const progressRef = useRef(progress);
  progressRef.current = progress;

  // The drill's nouns: the level's nouns whose every form is certain
  // (engine/kasus.drillNoun). A gender the level has too few of borrows
  // from every level rather than repeating the same three words.
  const nounsBySlot = useMemo(() => {
    const adjSet = new Set((db.adj || []).map((a) => a.w.toLowerCase()));
    const all = (db.nouns || []).map((n) => drillNoun(n, adjSet)).filter(Boolean);
    const inLevel = all.filter((n) => levelFilter === "All" || lvlOf(n) === levelFilter);
    const out = {};
    for (const s of ["m", "f", "n"]) {
      const lv = inLevel.filter((n) => n.slot === s);
      out[s] = lv.length >= 8 ? lv : all.filter((n) => n.slot === s);
    }
    return out;
  }, [db, levelFilter]);

  const cells = useMemo(
    () => cellsFor({ cases: f.cases, slots: f.slots, dets: f.dets, adjModes: f.adj })
      .filter((c) => f.contexts.some((ctx) => contextFits(ctx, c.kase))),
    [f]
  );

  const buildRound = useCallback(() => {
    if (!cells.length) return [];
    const order = weakFirst(cells, (c) => progressRef.current[keyOf(KASUS_CAT_ID, { w: cellId(c) })]);
    const qs = [];
    for (let i = 0; qs.length < ROUND && i < ROUND * 4; i++) {
      const cell = order[i % order.length];
      const ctxs = f.contexts.filter((ctx) => contextFits(ctx, cell.kase));
      const q = buildQuestion(cell, nounsBySlot, ctxs[Math.floor(Math.random() * ctxs.length)]);
      if (q) qs.push(q);
    }
    return qs;
  }, [cells, f.contexts, nounsBySlot]);

  const [queue, setQueue] = useState([]);
  const [idx, setIdx] = useState(0);
  const [chosen, setChosen] = useState(null); // the option picked / text typed
  const [typed, setTyped] = useState("");
  const [results, setResults] = useState([]);
  const [done, setDone] = useState(false);
  const [showGrid, setShowGrid] = useState(false);
  // Six rows of chips push the question below the fold on a phone, so the
  // panel folds to a one-line summary once you have set it up.
  const [open, setOpenState] = useState(filtersOpen);
  const setOpen = (v) => { filtersOpen = v; setOpenState(v); };
  const inputRef = useRef(null);

  const restart = useCallback(() => {
    setQueue(buildRound()); setIdx(0); setChosen(null); setTyped(""); setResults([]); setDone(false);
  }, [buildRound]);

  // A new filter selection deals a new round.
  useEffect(() => { restart(); /* eslint-disable-next-line */ }, [f.cases, f.slots, f.dets, f.adj, f.contexts, levelFilter]);

  const q = queue[idx];

  const grade = useCallback((given) => {
    if (!q || chosen !== null) return;
    const ok = f.mode === "type"
      ? q.accepted.map(normalize).includes(normalize(given))
      : given === q.answer;
    setChosen(given);
    setResults((r) => [...r, { q, ok, given }]);
    const k = keyOf(KASUS_CAT_ID, { w: cellId(q.cell) });
    const np = { ...progressRef.current, [k]: applyAnswer(progressRef.current[k], ok) };
    setProgress(np);
    saveProgress(np);
    recordAnswer?.(1);
  }, [q, chosen, f.mode, setProgress, recordAnswer]);

  const next = useCallback(() => {
    if (chosen === null) return;
    if (idx + 1 >= queue.length) { setDone(true); return; }
    setIdx(idx + 1); setChosen(null); setTyped("");
  }, [chosen, idx, queue.length]);

  useEffect(() => { if (f.mode === "type" && chosen === null) inputRef.current?.focus(); }, [idx, chosen, f.mode]);

  useEffect(() => {
    const onKey = (e) => {
      if (e.metaKey || e.ctrlKey || e.altKey) return;
      if (done) { if (e.key === "Enter" && !isTypingTarget(e.target)) { restart(); e.preventDefault(); } return; }
      if (chosen !== null) {
        if (e.key === "Enter" || (!isTypingTarget(e.target) && (e.key === " " || e.key === "ArrowRight"))) { next(); e.preventDefault(); }
        return;
      }
      if (isTypingTarget(e.target) || f.mode !== "mc" || !q) return;
      const n = parseInt(e.key, 10);
      if (n >= 1 && n <= q.options.length) { grade(q.options[n - 1]); e.preventDefault(); }
    };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [done, chosen, q, f.mode, grade, next, restart]);

  const summary = [
    f.cases.map((c) => CASE_SHORT[c]).join(" "),
    f.slots.map((s) => (s === "pl" ? "Pl" : ART_NOM[s])).join(" "),
    f.dets.map((d) => (d === "def" ? "der" : d === "none" ? "Ø" : d)).join(" "),
    f.adj.length === 2 ? "±Adj" : f.adj[0] === "adj" ? "+Adj" : "−Adj",
    f.contexts.map((c) => CONTEXTS.find((x) => x.value === c).label).join(", "),
  ].join(" · ");

  const filters = (
    <div style={{ background: COLORS.surface, border: `1px solid ${COLORS.border}`, borderRadius: 12, padding: open ? "10px 12px 6px" : "8px 12px", marginBottom: 12 }}>
      <button onClick={() => setOpen(!open)} aria-expanded={open}
        style={{ width: "100%", display: "flex", justifyContent: "space-between", alignItems: "center", gap: 8, background: "transparent", border: "none", padding: 0, cursor: "pointer", marginBottom: open ? 8 : 0, textAlign: "left" }}>
        <span style={{ fontSize: 12, color: MUTE, minWidth: 0 }}>{summary}</span>
        <span style={{ fontSize: 12, color: "#fda4af", whiteSpace: "nowrap", fontWeight: 600 }}>{open ? "Fertig ▴" : "Anpassen ▾"}</span>
      </button>
      {open && <>
      <ChipRow label="Fall" value={f.cases} onChange={(v) => set({ cases: v })}
        options={CASES.map((c) => ({ value: c, label: CASE_SHORT[c] }))} />
      <ChipRow label="Genus" value={f.slots} onChange={(v) => set({ slots: v })}
        options={SLOTS.map((s) => ({ value: s, label: s === "pl" ? "Plural" : `${ART_NOM[s]} (${SLOT_SHORT[s]})` }))} />
      <ChipRow label="Artikel" value={f.dets} onChange={(v) => set({ dets: v })}
        options={DETS.map((d) => ({ value: d, label: DET_LABEL[d] }))} />
      <ChipRow label="Adjektiv" value={f.adj} onChange={(v) => set({ adj: v })}
        options={[{ value: "adj", label: "mit Adjektiv" }, { value: "-", label: "ohne" }]} />
      <ChipRow label="Kontext" value={f.contexts} onChange={(v) => set({ contexts: v })} options={CONTEXTS} />
      <ChipRow label="Antwort" value={[f.mode]} single onChange={([v]) => set({ mode: v })}
        options={[{ value: "mc", label: "Auswählen" }, { value: "type", label: "Tippen" }]} />
      </>}
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginTop: open ? 2 : 4, gap: 8, flexWrap: "wrap" }}>
        <span style={{ fontSize: 11, color: FAINT }}>{cells.length} Kombinationen · Schwaches kommt zuerst</span>
        <button onClick={() => setShowGrid(!showGrid)}
          style={{ background: "transparent", border: "none", color: "#fda4af", fontSize: 12, cursor: "pointer", padding: "4px 0" }}>
          {showGrid ? "Schwachstellen ausblenden" : "Schwachstellen zeigen"}
        </button>
      </div>
      {showGrid && <KasusGrid progress={progress} onPick={(kase, slot) => { set({ cases: [kase], slots: [slot] }); setShowGrid(false); }} />}
    </div>
  );

  if (!cells.length) {
    return <div>{filters}<Empty>Diese Auswahl ergibt keine Kombination — „ein“ hat keinen Plural, „ohne Artikel“ geht nur im Plural mit Adjektiv, und nach einer Präposition steht nie der Nominativ.</Empty></div>;
  }

  if (done) {
    const score = results.filter((r) => r.ok).length;
    const missed = results.filter((r) => !r.ok);
    return (
      <div>
        {filters}
        <div className="dm-reveal" style={{ textAlign: "center" }}>
          <div style={{ fontSize: 13, color: MUTE, letterSpacing: 1, textTransform: "uppercase" }}>Runde fertig</div>
          <div style={{ fontSize: 52, fontWeight: 800, color: DRILL_ACCENT, margin: "4px 0" }}>{score}/{results.length}</div>
        </div>
        {missed.length > 0 && (
          <div style={{ background: COLORS.surface, border: `1px solid ${COLORS.border}`, borderRadius: 12, padding: 14, margin: "12px 0" }}>
            <div style={{ fontSize: 12, color: FAINT, marginBottom: 8, textTransform: "uppercase", letterSpacing: 0.5 }}>Nochmal ansehen ({missed.length})</div>
            {missed.map(({ q: m, given }, i) => (
              <div key={i} style={{ padding: "7px 0", borderTop: i ? "1px solid #1f1f1f" : "none" }}>
                <div style={{ fontSize: 14.5 }}>
                  <b style={{ color: COLORS.successText }}>{m.answer}</b>
                  <span style={{ color: COLORS.dangerText, fontSize: 12.5, marginLeft: 8, textDecoration: "line-through" }}>{given || "—"}</span>
                </div>
                <div style={{ fontSize: 12, color: MUTE, marginTop: 2 }}>{m.why}</div>
              </div>
            ))}
          </div>
        )}
        <KasusGrid progress={progress} onPick={(kase, slot) => set({ cases: [kase], slots: [slot] })} />
        <button onClick={restart}
          style={{ marginTop: 14, width: "100%", background: DRILL_ACCENT, border: "none", borderRadius: 12, padding: "14px", color: "#fff", fontSize: 15, fontWeight: 700, cursor: "pointer" }}>
          Neue Runde →
        </button>
      </div>
    );
  }

  if (!q) return <div>{filters}<Empty>Keine Nomen für diese Auswahl.</Empty></div>;

  const slot = q.number === "pl" ? "pl" : q.noun.slot;
  const detWord = q.det === "def" ? ART_NOM[slot] : q.det === "none" ? "–" : q.det;
  const header = q.context === "plain"
    ? CASE_LABEL[q.kase]
    : q.context === "twoway" ? `${q.where === "wohin" ? "Wohin?" : "Wo?"}  ${q.prep} + …` : `${q.prep} + …`;
  const isOk = chosen !== null && results[results.length - 1]?.ok;

  return (
    <div>
      {filters}
      <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 10 }}>
        <div style={{ flex: 1, height: 5, background: "#1f1f1f", borderRadius: 999 }}>
          <div style={{ width: `${((idx + (chosen !== null ? 1 : 0)) / queue.length) * 100}%`, height: 5, background: DRILL_ACCENT, borderRadius: 999, transition: "width .3s" }} />
        </div>
        <span style={{ fontSize: 12, color: FAINT, fontVariantNumeric: "tabular-nums" }}>{idx + 1}/{queue.length}</span>
      </div>

      <div style={{ background: "#131313", border: `1px solid ${DRILL_ACCENT}33`, borderRadius: 16, padding: "18px 18px 20px", marginBottom: 12 }}>
        <div style={{ fontSize: 12, color: FAINT, textTransform: "uppercase", letterSpacing: 0.5 }}>
          {q.context === "plain" ? "Setze in den Fall" : q.context === "twoway" ? "Wechselpräposition" : "Welcher Fall nach der Präposition?"}
        </div>
        <div style={{ fontSize: 26, fontWeight: 800, color: COLORS.txtStrong, marginTop: 6, lineHeight: 1.2 }}>{header}</div>
        <div style={{ display: "flex", gap: 6, flexWrap: "wrap", marginTop: 12, alignItems: "center" }}>
          <Block label="Artikel">{detWord}</Block>
          {q.adj && <Block label="Adjektiv">{q.adj}</Block>}
          <Block label={q.number === "pl" ? "Plural" : SLOT_LABEL[slot]} color={GENDER_COLOR[slot]}>
            {q.number === "pl" ? `die ${q.noun.pl}` : q.noun.w}
          </Block>
        </div>
        {q.noun.e && <div style={{ fontSize: 12, color: FAINT, marginTop: 8 }}>{q.noun.w} = {q.noun.e}</div>}

        {chosen !== null && (
          <div className="dm-reveal" role="status" aria-live="polite" style={{ marginTop: 14, borderTop: "1px solid #222", paddingTop: 12 }}>
            <div style={{ display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap" }}>
              <span style={{ fontSize: 14, color: isOk ? COLORS.successText : COLORS.dangerText, fontWeight: 700 }}>{isOk ? "Richtig ✓" : "Nicht ganz"}</span>
              <span lang="de" style={{ fontSize: 18, color: COLORS.successText, fontWeight: 800 }}>{q.answer}</span>
              <SpeakBtn text={q.answer} color={DRILL_ACCENT} size={28} />
            </div>
            <div style={{ fontSize: 12.5, color: "#9aa6b6", marginTop: 6, lineHeight: 1.5 }}>💡 {q.why}</div>
          </div>
        )}
      </div>

      {f.mode === "mc" ? (
        <div style={{ display: "grid", gridTemplateColumns: "1fr", gap: 8 }}>
          {q.options.map((opt, i) => {
            let bg = "#171717", border = COLORS.borderSoft, color = TXT, mark = null;
            if (chosen !== null) {
              if (opt === q.answer) { bg = "#0a2a16"; border = COLORS.success; color = "#5eead4"; mark = "✓"; }
              else if (opt === chosen) { bg = "#2a0d0d"; border = COLORS.danger; color = COLORS.dangerText; mark = "✗"; }
              else color = "#6b7280";
            }
            return (
              <button key={opt} lang="de" onClick={() => grade(opt)} disabled={chosen !== null}
                style={{ background: bg, border: `1.5px solid ${border}`, borderRadius: 12, padding: "12px 14px", color, fontSize: 15.5, fontWeight: 600, cursor: chosen ? "default" : "pointer", textAlign: "left", display: "flex", justifyContent: "space-between", gap: 8 }}>
                <span style={{ minWidth: 0, overflowWrap: "anywhere" }}><span style={{ color: FAINT, fontWeight: 400, marginRight: 8, fontSize: 12 }}>{i + 1}</span>{opt}</span>
                {mark && <b>{mark}</b>}
              </button>
            );
          })}
        </div>
      ) : (
        <form onSubmit={(e) => { e.preventDefault(); if (chosen === null && typed.trim()) grade(typed); }} style={{ display: "flex", gap: 8 }}>
          <input ref={inputRef} value={typed} onChange={(e) => setTyped(e.target.value)} disabled={chosen !== null}
            lang="de" autoCapitalize="off" autoCorrect="off" spellCheck={false} placeholder="z. B. mit dem neuen Tisch"
            aria-label="Deine Antwort"
            style={{ flex: 1, minWidth: 0, background: "#171717", border: `1.5px solid ${chosen === null ? COLORS.borderSoft : isOk ? COLORS.success : COLORS.danger}`, borderRadius: 12, padding: "12px 14px", color: TXT, fontSize: 16 }} />
          {chosen === null && (
            <button type="submit" style={{ background: DRILL_ACCENT, border: "none", borderRadius: 12, padding: "0 16px", color: "#fff", fontWeight: 700, cursor: "pointer" }}>Prüfen</button>
          )}
        </form>
      )}

      {chosen !== null && (
        <button onClick={next}
          style={{ marginTop: 12, width: "100%", background: DRILL_ACCENT, border: "none", borderRadius: 12, padding: "14px", color: "#fff", fontSize: 15, fontWeight: 700, cursor: "pointer" }}>
          {idx + 1 >= queue.length ? "Runde beenden" : "Weiter →"}
        </button>
      )}
      <div className="dm-kbd-tip" style={{ textAlign: "center", marginTop: 10, fontSize: 11, color: "#4a4f59" }}>
        {f.mode === "mc" ? `Tasten 1–${q.options.length} · Enter für weiter` : "Enter zum Prüfen, dann Enter für weiter"}
      </div>
    </div>
  );
}

function Block({ label, color, children }) {
  return (
    <span style={{ display: "inline-flex", flexDirection: "column", background: "#1a1a1a", border: `1px solid ${color ? color + "66" : COLORS.borderSoft}`, borderRadius: 10, padding: "5px 10px", minWidth: 0 }}>
      <span style={{ fontSize: 9.5, color: FAINT, textTransform: "uppercase", letterSpacing: 0.4 }}>{label}</span>
      <span lang="de" style={{ fontSize: 16, fontWeight: 700, color: color || COLORS.txtStrong, overflowWrap: "anywhere" }}>{children}</span>
    </span>
  );
}

function Empty({ children }) {
  return <div style={{ color: FAINT, textAlign: "center", padding: "24px 10px", fontSize: 13, lineHeight: 1.6 }}>{children}</div>;
}

// ── Weak-spot grid ────────────────────────────────────────────
// Case × gender/number, summed over every determiner and adjective cell.
// Tap a square to drill just that combination.
export function KasusGrid({ progress, onPick }) {
  const agg = {};
  const prefix = KASUS_CAT_ID + ":";
  for (const [k, p] of Object.entries(progress)) {
    if (!k.startsWith(prefix) || !p || !p.total) continue;
    const [kase, slot] = k.slice(prefix.length).split("|");
    const a = (agg[`${kase}|${slot}`] ||= { c: 0, t: 0 });
    a.c += p.correct; a.t += p.total;
  }
  return (
    <div style={{ marginTop: 10 }}>
      <div style={{ fontSize: 11, color: FAINT, textTransform: "uppercase", letterSpacing: 0.5, marginBottom: 6 }}>Schwachstellen — Trefferquote je Feld</div>
      <div style={{ display: "grid", gridTemplateColumns: "44px repeat(4, 1fr)", gap: 4 }}>
        <span />
        {SLOTS.map((s) => <span key={s} style={{ fontSize: 11, color: MUTE, textAlign: "center" }}>{s === "pl" ? "Pl" : ART_NOM[s]}</span>)}
        {CASES.map((c) => (
          <Row key={c} c={c} agg={agg} onPick={onPick} />
        ))}
      </div>
    </div>
  );
}

function Row({ c, agg, onPick }) {
  return (
    <>
      <span style={{ fontSize: 11.5, color: MUTE, alignSelf: "center" }}>{CASE_SHORT[c]}</span>
      {SLOTS.map((s) => {
        const a = agg[`${c}|${s}`];
        const pct = a ? Math.round((a.c / a.t) * 100) : null;
        const bg = pct == null ? "#161616" : pct >= 85 ? "#0a2a16" : pct >= 60 ? "#2a220a" : "#2a0d0d";
        const fg = pct == null ? "#3f4651" : pct >= 85 ? COLORS.successText : pct >= 60 ? COLORS.warn : COLORS.dangerText;
        return (
          <button key={s} onClick={() => onPick(c, s)} title={`${CASE_LABEL[c]} · ${SLOT_LABEL[s]}${a ? ` — ${a.c}/${a.t} richtig` : " — noch nicht geübt"}`}
            style={{ background: bg, border: `1px solid ${COLORS.border}`, borderRadius: 7, padding: "7px 0", color: fg, fontSize: 12, fontWeight: 700, cursor: "pointer", fontVariantNumeric: "tabular-nums" }}>
            {pct == null ? "·" : `${pct}%`}
          </button>
        );
      })}
    </>
  );
}
