# Content spec for the Spickzettel. Markup inside strings:
#   `x`   German (mono)       **x** bold (the ending that matters)
#   _x_   English gloss       {m:x} {f:x} {n:x} {p:x} gender colour
#   {nom:x} {akk:x} {dat:x} {gen:x} case colour     [text](#id) link
#   \n    line break
# Table heads: "m:maskulin" colours the column; gc=True also colours the body.
# Notes: ("label", "text"); a label starting with "!" is a hack (amber).

def T(cap, head, rows, gc=False, rh=True, full=False):
    return dict(k="t", cap=cap, head=head, rows=rows, gc=gc, rh=rh, full=full)

def N(*rows):
    return dict(k="n", rows=list(rows))

def B(id, title, lvl, tags, *items):
    return dict(id=id, title=title, lvl=lvl, tags=tags, items=list(items))

G4 = ["", "m:maskulin", "f:feminin", "n:neutrum", "p:Plural"]
PERS = ["", "ich", "du", "er/sie/es", "wir", "ihr", "sie/Sie"]

SECTIONS = []

# ─────────────────────────── Grundgesetze
SECTIONS.append(("sec-gesetze", "Grundgesetze", [
  B("ref-gesetze", "Die zehn Grundgesetze", "A1", "Regeln, an denen alles hängt",
    T("Nomen & Kasus", ["#", "Gesetz", "Was das heißt", "Beispiel"], [
      ["1", "Jedes Nomen hat ein Genus", "every noun is {m:der}, {f:die} or {n:das} — grammar, not meaning. Learn article + plural with the noun, as one chunk. Compounds take the gender of the **last** part. Nouns are always capitalised. [→ Genus](#ref-genus)", "{m:der Tisch}, die Tische\n{n:das Mädchen} _(neuter!)_\n{f:die Tür} + {m:der Schlüssel} → {m:der Türschlüssel}"],
      ["2", "Der Kasus zeigt die Rolle", "the subject is {nom:Nominativ}, the thing acted on is {akk:Akkusativ}, the receiver is {dat:Dativ}. After a preposition or certain verbs, **they** decide the case. [→ Kasus](#ref-kasus)", "{nom:Ich} gebe {dat:dem Kind} {akk:den Ball}.\nmit → Dat · für → Akk · helfen → Dat"],
      ["3", "Der Artikel trägt den Kasus", "the noun barely changes — the article (and adjective ending) shows the case. In the Akkusativ **only masculine** changes; f, n and plural stay as in the Nominativ. In the Dativ **all** of them change.", "{akk:den Mann} · {akk:die Frau} · {akk:das Kind}\nDat: {dat:dem · der · dem · den …n}"],
    ], full=True),
    T("Verb & Satzbau", ["#", "Gesetz", "Was das heißt", "Beispiel"], [
      ["4", "Das Verb passt zum Subjekt", "the conjugated verb takes the ending of its subject: ich -e · du -st · er/sie/es -t · wir -en · ihr -t · sie/Sie -en. [→ Präsens](#ref-praesens)", "ich wohn**e** · du wohn**st** · sie wohn**t**"],
      ["5", "Aussage & W-Frage: Verb auf Position 2", "Position 1 holds **one element** (one or many words). Usually the subject — if anything else goes first, the subject moves right **after** the verb.", "Ich **gehe** heute ins Kino.\nHeute **gehe** ich ins Kino.\nWann **gehst** du ins Kino?"],
      ["6", "Ja/Nein-Frage & Imperativ: Verb auf Position 1", "no question word, or a command → the verb comes first.", "**Gehst** du heute ins Kino?\n**Geh** ins Kino!"],
      ["7", "Satzklammer", "if the verb has two parts, the conjugated part is at position 2 and the rest goes to the **very end**: infinitive after a modal, Partizip II, separable prefix. [→ Satzbau](#ref-algorithmus)", "Ich **muss** morgen **arbeiten**.\nIch **habe** gestern **gearbeitet**.\nIch **stehe** früh **auf**."],
      ["8", "Nebensatz: konjugiertes Verb ans Ende", "after weil, dass, wenn, ob, obwohl, als … (and in relative clauses) the conjugated verb goes **last** — after any infinitive or Partizip. Separable verbs join up again. [→ Nebensatz](#ref-nebensatz)", "…, weil ich müde **bin**.\n…, weil ich arbeiten **muss**.\n…, weil ich früh **aufstehe**."],
      ["9", "Nebensatz zuerst → Verb, Komma, Verb", "a Nebensatz at the start **is** position 1, so the main clause starts with its verb.", "Weil ich müde **bin**, **gehe** ich ins Bett."],
      ["10", "und · aber · oder · denn · sondern = Position 0", "these five just link two main clauses and change nothing — the next clause keeps normal order. (deshalb, trotzdem, dann … **do** take position 1.) [→ Konjunktionen](#ref-konjunktionen)", "…, **denn** ich **bin** müde.\n…, **deshalb bleibe** ich zu Hause."],
    ], full=True),
    N(("Merke", "Position 2 means second **element**, not second word: `**Am nächsten Montag** **fahre** ich …` — three words, still position 1."),
      ("!Satz in 3 Fragen", "1 · Which sentence type? → verb 2nd (statement, W-question), 1st (yes/no, command) or last (Nebensatz). 2 · Two verb parts? → the second part goes to the end. 3 · Who does what to whom? → Nom · Akk · Dat."))),
]))

# ─────────────────────────── Nomen & Artikel
SECTIONS.append(("sec-nomen", "Nomen & Artikel", [
  B("ref-kasus", "Artikel & Kasus", "A1", "der · die · das · ein · kein",
    T("Bestimmter Artikel", G4, [
      ["Nominativ", "der", "die", "das", "die"],
      ["Akkusativ", "**den**", "die", "das", "die"],
      ["Dativ", "**dem**", "**der**", "**dem**", "**den** …n"],
      ["Genitiv", "**des** …(e)s", "**der**", "**des** …(e)s", "**der**"],
    ], gc=True),
    T("Unbestimmter / negativer Artikel", G4, [
      ["Nominativ", "ein / kein", "eine / keine", "ein / kein", "— / keine"],
      ["Akkusativ", "**einen / keinen**", "eine / keine", "ein / kein", "— / keine"],
      ["Dativ", "**einem / keinem**", "**einer / keiner**", "**einem / keinem**", "— / **keinen** …n"],
      ["Genitiv", "**eines / keines**", "**einer / keiner**", "**eines / keines**", "— / **keiner**"],
    ], gc=True),
    T("Welcher Kasus?", ["Kasus", "Frage", "Job", "Präpositionen / Verben", "Beispiel"], [
      ["Nominativ", "Wer? Was?", "subject; after sein · werden · bleiben · heißen", "—", "**Der Mann** arbeitet."],
      ["Akkusativ", "Wen? Was?", "direct object", "durch für gegen ohne um bis entlang", "Ich sehe **den Mann**."],
      ["Dativ", "Wem?", "indirect object", "aus außer bei mit nach seit von zu · helfen, danken …", "Ich helfe **dem Mann**."],
      ["Genitiv", "Wessen?", "possession", "wegen trotz während statt außerhalb", "das Auto **des Mannes**"],
    ], full=True),
    N(("Merke", "Only masculine changes in the Akkusativ (`der → den`). The Dativ row is the one to chant: `dem · der · dem · den`."),
      ("!Hack · r → n", "Akk masc: turn the final r into n — `der → den`, `dieser → diesen`, `jeder → jeden`. ein-words add -en: `ein → einen`, `mein → meinen`."),
      ("Dativ Plural", "`den` + noun in -n: `mit den Kinder**n**`, `aus den Häuser**n**`. Not after -n/-s: `mit den Autos`."),
      ("Ein Satz, drei Kasus", "`{nom:Der Mann} gibt {dat:dem Jungen} {akk:den Hund}.` = `{akk:Den Hund} gibt {nom:der Mann} {dat:dem Jungen}.` — cases carry the roles, so order is free.")),
  ),
  B("ref-genus", "Genus erraten", "A1", "welcher Artikel? Endungen & Bedeutung",
    T("Nach der Endung", ["Artikel", "Endungen", "Beispiele"], [
      ["{m:der}", "-er (Person) · -ling · -ismus · -ant · -ent · -ist · -or · -eur · -us · -ich · -ig", "Lehrer, Frühling, Kapitalismus, Student, Motor, Ingenieur, Teppich, Honig"],
      ["{f:die}", "-e · -ung · -heit · -keit · -schaft · -ion · -tät · -ei · -ik · -ur · -anz · -enz · -in", "Lampe, Wohnung, Freiheit, Möglichkeit, Nation, Universität, Bäckerei, Musik, Natur, Lehrerin"],
      ["{n:das}", "-chen · -lein · -ment · -um · -ma · -tum · -nis · -o · Ge-", "Mädchen, Fräulein, Dokument, Museum, Thema, Eigentum, Ergebnis, Auto, Gebäude"],
    ], full=True),
    T("Nach der Bedeutung", ["Artikel", "Kategorie", "Beispiele"], [
      ["{m:der}", "Tage, Monate, Jahreszeiten · Wetter · Himmelsrichtungen · Automarken · Alkohol (außer Bier) · männliche Personen", "Montag, Mai, Sommer, Regen, Norden, BMW, Wein, Vater"],
      ["{f:die}", "Blumen, Bäume · Zahlen als Nomen · Schiffe, Flugzeuge · die meisten deutschen Flüsse · weibliche Personen", "Rose, Eiche, Eins, Titanic, Donau, Mutter"],
      ["{n:das}", "Metalle · Farben als Nomen · Verben als Nomen · Sprachen · Buchstaben · junge Lebewesen", "Gold, Blau, Essen, Deutsch, A, Baby, Kind"],
    ], full=True),
    N(("!-e → die", "~9 of 10. Exceptions: `{m:der Name, Käse, Junge, Kollege, Kunde, Löwe}` · `{n:das Ende, Auge, Interesse, Gebäude}`"),
      ("!Ge- → das", "`das Gebäude, Gemüse, Gespräch, Geschenk, Gebirge, Geld`"),
      ("!-chen / -lein → das", "overrides everything: `der Hund → {n:das Hündchen}`, `das Mädchen`, `das Brötchen`"),
      ("Komposita", "last part decides: `das Haus + die Tür = {f:die Haustür}` · `der Handschuh · die Handtasche · das Handtuch`")),
  ),
  B("ref-plural", "Plural", "A1", "fünf Muster",
    T("", ["Endung", "typisch für", "Singular", "Plural"], [
      ["-(e)n", "fast alle femininen", "die Frau · Blume · Zeitung", "Frau**en** · Blume**n** · Zeitung**en**"],
      ["-e (+ Umlaut)", "viele maskuline, einige neutrale", "der Tisch · Stuhl", "Tisch**e** · St**ü**hl**e**"],
      ["-er (+ Umlaut)", "viele kurze neutrale", "das Kind · Buch", "Kind**er** · B**ü**ch**er**"],
      ["-s", "Fremdwörter, Abkürzungen, Vokal-Ende", "das Auto · Handy · die Oma", "Auto**s** · Handy**s** · Oma**s**"],
      ["— (+ Umlaut)", "-er · -en · -el · -chen · -lein", "der Lehrer · Vater · das Mädchen", "Lehrer · V**ä**ter · Mädchen"],
      ["-in → -innen", "weibliche Berufe", "die Lehrerin", "Lehrer**innen**"],
    ]),
    N(("!Nach Genus raten", "`{f:die}` → -(e)n · `{m:der}` → -e (+Umlaut) · `{n:das}` → -e / -er · already -er/-en/-el/-chen → no change"),
      ("Artikel", "Plural article is always `{p:die}`; gender only matters again in the Dativ Plural (`den …n`)."),
      ("Nur Singular", "`das Obst, Gemüse, Geld, die Milch, Musik` → count with `zwei Stück Obst, drei Sorten Gemüse`"),
      ("Nur Plural", "`die Eltern, Leute, Ferien, Kosten, USA` → `Die Leute **sind** nett.`")),
  ),
  B("ref-nomendekl", "Nomen deklinieren", "A1", "Singular → Plural, alle vier Kasus",
    T("", ["", "m:der Tisch", "p:Plural", "f:die Blume", "p:Plural", "n:das Kind", "p:Plural", "mein Freund", "p:Plural"], [
      ["Nominativ", "der Tisch", "die Tisch**e**", "die Blume", "die Blume**n**", "das Kind", "die Kind**er**", "mein Freund", "mein**e** Freunde"],
      ["Akkusativ", "**den** Tisch", "die Tisch**e**", "die Blume", "die Blume**n**", "das Kind", "die Kind**er**", "mein**en** Freund", "mein**e** Freunde"],
      ["Dativ", "**dem** Tisch", "**den** Tisch**en**", "**der** Blume", "**den** Blume**n**", "**dem** Kind", "**den** Kinder**n**", "mein**em** Freund", "mein**en** Freunde**n**"],
      ["Genitiv", "**des** Tisch**es**", "**der** Tisch**e**", "**der** Blume", "**der** Blume**n**", "**des** Kind**es**", "**der** Kind**er**", "mein**es** Freund**es**", "mein**er** Freunde"],
    ], gc=True, full=True),
    T("Genitiv: -s oder -es?", ["Endung", "wann", "Beispiele"], [
      ["-es", "one syllable; ends in -s -ß -x -z -sch", "des Mann**es**, Haus**es**, Kind**es**, Platz**es**"],
      ["-s", "two+ syllables, esp. -er -en -el -chen", "des Lehrer**s**, Wagen**s**, Mädchen**s**, Auto**s**"],
      ["—", "every feminine noun", "der Frau, der Blume"],
    ]),
    N(("Nur zwei Stellen", "The noun itself changes only in **Gen Sg m/n** (`-(e)s`) and **Dat Pl** (`-n`). Everywhere else the article does the work."),
      ("!Plural = 3 Formen", "`die · die · den …n · der` — chant it and the plural is done."),
      ("ein im Plural", "`ein` has no plural: `ein Freund → Freunde`. `kein`/possessives copy der-forms: `keine · keine · keinen · keiner`"),
      ("Kein Dativ-n", "after plural -n/-s: `mit den Blumen`, `in den Autos`"),
      ("Ausnahme", "masculine weak nouns → [N-Deklination](#ref-ndekl)")),
  ),
  B("ref-possessiv", "Possessiv-, Demonstrativ- & Frageartikel", "A1", "mein · ihr · sein · dies- · welch- · jed-",
    T("Stämme", ["ich", "du", "er", "sie", "es", "wir", "ihr", "sie", "Sie"], [
      ["mein", "dein", "sein", "ihr", "sein", "unser", "euer", "ihr", "Ihr"],
    ], rh=False),
    T("mein- (= ein-Endungen)", G4, [
      ["Nominativ", "mein", "meine", "mein", "meine"],
      ["Akkusativ", "**meinen**", "meine", "mein", "meine"],
      ["Dativ", "**meinem**", "**meiner**", "**meinem**", "**meinen** …n"],
      ["Genitiv", "**meines**", "**meiner**", "**meines**", "**meiner**"],
    ], gc=True),
    T("dies- / welch- / jed- (= der-Endungen)", G4, [
      ["Nominativ", "dieser", "diese", "dieses", "diese"],
      ["Akkusativ", "**diesen**", "diese", "dieses", "diese"],
      ["Dativ", "**diesem**", "**dieser**", "**diesem**", "**diesen** …n"],
      ["Genitiv", "**dieses**", "**dieser**", "**dieses**", "**dieser**"],
    ], gc=True),
    T("Alle Formen ausgeschrieben", ["Stamm", "— \nm Nom · n Nom/Akk", "-e\nf + pl Nom/Akk", "-en\nm Akk · pl Dat", "-em\nm + n Dat", "-er\nf Dat/Gen · pl Gen", "-es\nm + n Gen"], [
      ["mein _my_", "mein", "meine", "meinen", "meinem", "meiner", "meines"],
      ["dein _your_", "dein", "deine", "deinen", "deinem", "deiner", "deines"],
      ["sein _his/its_", "sein", "seine", "seinen", "seinem", "seiner", "seines"],
      ["ihr _her/their_", "ihr", "ihre", "ihren", "ihrem", "ihrer", "ihres"],
      ["unser _our_", "unser", "unsere", "unseren", "unserem", "unserer", "unseres"],
      ["euer _your pl._", "euer", "eure", "euren", "eurem", "eurer", "eures"],
      ["Ihr _your formal_", "Ihr", "Ihre", "Ihren", "Ihrem", "Ihrer", "Ihres"],
      ["kein _no_", "kein", "keine", "keinen", "keinem", "keiner", "keines"],
    ], full=True),
    N(("!sein oder ihr?", "Stem = owner, ending = thing owned: `Die Frau und **ihr** Mann` · `Der Mann und **seine** Frau`"),
      ("!Zwei Familien", "der-Wörter `der dieser jeder welcher mancher solcher alle` → der-Endungen · ein-Wörter `ein kein mein dein sein ihr unser euer Ihr` → ein-Endungen"),
      ("Ohne Nomen", "switches to der-endings: `Welcher Mantel ist **deiner**? — **Meiner**.` · `Hast du **eins**?`"),
      ("Fallen", "`euer` drops e: `eu**re** Autos, eu**ren** Bruder` · `ihr` = her/their, `Ihr` = your (formal)"),
      ("Im Satz", "`Ich kenne **ihren** Mann.` _Akk m_ · `mit **seiner** Schwester` _Dat f_ · `das Auto **ihres** Vaters` _Gen m_ · `bei **unseren** Eltern` _Dat pl_")),
  ),
  B("ref-pronomen", "Personalpronomen", "A1", "mich mir · ihn ihm · Dativverben · Reihenfolge",
    T("", ["Kasus", "ich", "du", "m:er", "f:sie", "n:es", "wir", "ihr", "p:sie", "Sie"], [
      ["Nominativ", "ich", "du", "er", "sie", "es", "wir", "ihr", "sie", "Sie"],
      ["Akkusativ", "mich", "dich", "**ihn**", "sie", "es", "uns", "euch", "sie", "Sie"],
      ["Dativ", "mir", "dir", "**ihm**", "**ihr**", "**ihm**", "uns", "euch", "**ihnen**", "Ihnen"],
    ], gc=True),
    T("Verben mit Dativ", ["Typ", "Verben", "Beispiel"], [
      ["nur Dativ", "helfen danken gefallen gehören antworten glauben passen stehen schmecken gratulieren folgen wehtun begegnen zuhören vertrauen", "Das Buch gehört **mir**."],
      ["Dativ + Akk", "geben zeigen schenken bringen schicken erklären empfehlen leihen erzählen anbieten kaufen", "Ich schenke **ihr** (D) **einen Ring** (A)."],
    ], full=True),
    T("Reihenfolge von zwei Objekten", ["Objekte", "Regel", "Beispiel"], [
      ["Nomen + Nomen", "Dativ zuerst", "Ich gebe dem Mann das Buch."],
      ["Pronomen + Pronomen", "Akkusativ zuerst", "Ich gebe es ihm."],
      ["gemischt", "Pronomen zuerst", "Ich gebe ihm das Buch. · Ich gebe es dem Mann."],
    ]),
    N(("Genus zählt", "pronoun copies the noun's gender: `Der Tisch? **Er** ist alt. Ich kaufe **ihn**.`"),
      ("!Pronomen drängeln", "as far left as possible, right after the verb: `Gestern habe **ich es ihm** gegeben.`"),
      ("man", "conjugates like er; Akk `einen`, Dat `einem`: `Hier **darf man** nicht rauchen.`"),
      ("es", "dummy subject: `Es regnet. Es ist acht Uhr. Es gibt …`"),
      ("jemand · niemand", "`Ich habe **niemanden** gesehen. Hast du **etwas** gehört?`")),
  ),
  B("ref-ndekl", "N-Deklination", "B1", "schwache Nomen: den Studenten",
    T("", ["", "Singular", "Plural"], [
      ["Nominativ", "der Student", "die Studenten"],
      ["Akkusativ", "den Student**en**", "die Studenten"],
      ["Dativ", "dem Student**en**", "den Studenten"],
      ["Genitiv", "des Student**en**", "der Studenten"],
    ]),
    T("Wer gehört dazu?", ["Gruppe", "Beispiele"], [
      ["mask. auf -e (Person/Tier)", "Junge, Kollege, Kunde, Neffe, Löwe, Affe, Franzose"],
      ["Fremdwort, Betonung am Ende", "Student, Polizist, Journalist, Präsident, Fotograf, Architekt, Soldat, Elefant"],
      ["Sonderfälle", "Herr (-n Sg, -en Pl), Mensch, Nachbar, Bauer"],
      ["gemischt: Gen -ns", "Name → des Namens · Gedanke, Wille, Glaube, Buchstabe · das Herz → des Herzens"],
    ]),
    N(("!Hack", "masculine person + plural in -en → assume N-Deklination. Except -or: `der Doktor, den Doktor, des Doktors`. `Ich kenne den Herr**n**. Ich helfe dem Nachbar**n**.`")),
  ),
]))

# ─────────────────────────── Verben
SECTIONS.append(("sec-verben", "Verben", [
  B("ref-praesens", "Präsens", "A1", "Konjugation · sein haben werden · Vokalwechsel",
    T("", ["", "machen", "arbeiten\n-t/-d", "heißen\n-s/-ß/-z", "sein", "haben", "werden"], [
      ["ich", "mache", "arbeite", "heiße", "bin", "habe", "werde"],
      ["du", "mach**st**", "arbeit**e**st", "heiß**t**", "bist", "hast", "wirst"],
      ["er/sie/es", "mach**t**", "arbeit**e**t", "heißt", "ist", "hat", "wird"],
      ["wir", "mach**en**", "arbeiten", "heißen", "sind", "haben", "werden"],
      ["ihr", "mach**t**", "arbeit**e**t", "heißt", "seid", "habt", "werdet"],
      ["sie/Sie", "mach**en**", "arbeiten", "heißen", "sind", "haben", "werden"],
    ]),
    T("Vokalwechsel — nur du & er/sie/es", ["Wechsel", "Verben", "du", "er"], [
      ["a → ä", "fahren schlafen tragen fallen halten waschen gefallen einladen verlassen raten", "fährst", "fährt"],
      ["au → äu", "laufen", "läufst", "läuft"],
      ["e → i", "sprechen essen geben helfen treffen vergessen werfen sterben brechen nehmen", "sprichst", "spricht"],
      ["e → ie", "sehen lesen empfehlen stehlen geschehen", "siehst", "sieht"],
    ]),
    N(("man", "= er-form: `Man macht das so.`"),
      ("nehmen", "`du nimmst, er nimmt` (double m)"),
      ("!Präsens = Futur", "scheduled future uses the present: `Morgen **fahre** ich nach Berlin.`"),
      ("seit + Präsens", "still going on → present: `Ich **wohne** seit zwei Jahren in München.`")),
  ),
  B("ref-modal", "Modalverben", "A1", "können müssen dürfen sollen wollen mögen möchten",
    T("", ["", "können\n_ability_", "müssen\n_necessity_", "wollen\n_want_", "dürfen\n_permission_", "sollen\n_should_", "mögen\n_like_", "möchten\n_would like_"], [
      ["ich", "kann", "muss", "will", "darf", "soll", "mag", "möchte"],
      ["du", "kannst", "musst", "willst", "darfst", "sollst", "magst", "möchtest"],
      ["er/sie/es", "kann", "muss", "will", "darf", "soll", "mag", "möchte"],
      ["wir", "können", "müssen", "wollen", "dürfen", "sollen", "mögen", "möchten"],
      ["ihr", "könnt", "müsst", "wollt", "dürft", "sollt", "mögt", "möchtet"],
      ["sie/Sie", "können", "müssen", "wollen", "dürfen", "sollen", "mögen", "möchten"],
    ], full=True),
    T("Bedeutung", ["Verb", "Kern", "Beispiel"], [
      ["können", "ability · possibility · informal permission", "Ich kann schwimmen. Kann ich hier parken?"],
      ["müssen", "obligation from circumstances", "Ich muss arbeiten."],
      ["dürfen", "permission from someone", "Darf ich Sie etwas fragen?"],
      ["sollen", "instruction from outside", "Der Arzt sagt, ich soll mehr schlafen."],
      ["wollen", "strong own will (blunt)", "Ich will das nicht."],
      ["möchten", "polite 'would like'", "Ich möchte einen Kaffee, bitte."],
      ["mögen", "like — usually + noun", "Ich mag Kaffee."],
    ]),
    N(("Form", "ich = er, no ending: `ich kann, er kann`. Singular changes vowel (except sollen), plural = infinitive vowel."),
      ("!nicht müssen ≠ nicht dürfen", "`Du **musst nicht** kommen` = don't have to · `Du **darfst nicht** kommen` = must not"),
      ("Stellung", "infinitive at the end: `Ich **kann** heute nicht **kommen**.` Alone: `Ich muss nach Hause. Ich kann Deutsch.`")),
  ),
  B("ref-trennbar", "Trennbare & untrennbare Verben", "A1", "auf- an- aus- · be- ver- er-",
    T("", ["Typ", "Präfixe", "Präsens", "Partizip II"], [
      ["trennbar _betont_", "auf- an- aus- ein- mit- nach- vor- zu- ab- zurück- weg- los- fern- her- hin- um- durch-", "Ich stehe um 7 Uhr **auf**.", "auf**ge**standen"],
      ["untrennbar _unbetont_", "be- emp- ent- er- ge- miss- ver- zer-", "Ich **be**suche meine Familie.", "besucht (kein ge-)"],
    ], full=True),
    T("Wo landet das Präfix?", ["Satz", "Beispiel"], [
      ["Hauptsatz", "Der Zug **kommt** um 18 Uhr **an**."],
      ["mit Modalverb", "Ich **muss** früh **aufstehen**."],
      ["Perfekt", "Ich **bin** früh **aufgestanden**."],
      ["Nebensatz", "…, weil ich früh **aufstehe**."],
      ["zu-Infinitiv", "Es ist Zeit, **aufzustehen**."],
    ]),
    N(("!Betonung", "stress on prefix → separates: `**AN**rufen` ✓ · `be**SU**chen` ✗"),
      ("Merkspruch", "`be-ge-er-ver-zer-ent-emp-miss` — never separate, never take ge-"),
      ("Doppelgänger", "um- durch- über- unter- wieder- go either way: `Ich **ziehe um**` (move house) vs `Ich **umarme** dich` · `setze … über` vs `übersetze`")),
  ),
  B("ref-perfekt", "Perfekt & Partizip II", "A1", "haben/sein + ge-…-t/-en · 60 unregelmäßige",
    T("Bildung", ["Verbtyp", "Bildung", "Beispiel"], [
      ["regelmäßig", "ge- + Stamm + -t", "machen → **gemacht**"],
      ["Stamm -t/-d", "ge- + Stamm + -et", "arbeiten → **gearbeitet**"],
      ["unregelmäßig", "ge- + (neuer) Stamm + -en", "sprechen → **gesprochen**"],
      ["-ieren", "kein ge-, -t", "studieren → **studiert**"],
      ["trennbar", "Präfix + ge- + Rest", "einkaufen → **eingekauft**"],
      ["untrennbar", "kein ge-", "besuchen → **besucht**"],
    ]),
    T("haben oder sein?", ["Hilfsverb", "wann", "Verben"], [
      ["sein", "Bewegung A → B", "gehen fahren fliegen kommen laufen reisen umziehen steigen wandern schwimmen"],
      ["sein", "Zustandswechsel", "aufstehen einschlafen aufwachen werden sterben wachsen"],
      ["sein", "Sonderfälle", "sein bleiben passieren gelingen"],
      ["haben", "alles andere", "incl. every verb with an Akkusativ object"],
    ]),
    T("Unregelmäßige Verben", ["Infinitiv", "Präteritum", "Partizip II", "Infinitiv", "Präteritum", "Partizip II"], [
      ["sein", "war", "ist gewesen", "gehen", "ging", "ist gegangen"],
      ["haben", "hatte", "hat gehabt", "fahren", "fuhr", "ist gefahren"],
      ["werden", "wurde", "ist geworden", "kommen", "kam", "ist gekommen"],
      ["bleiben", "blieb", "ist geblieben", "laufen", "lief", "ist gelaufen"],
      ["fliegen", "flog", "ist geflogen", "schwimmen", "schwamm", "ist geschwommen"],
      ["aufstehen", "stand auf", "ist aufgestanden", "einschlafen", "schlief ein", "ist eingeschlafen"],
      ["sterben", "starb", "ist gestorben", "umziehen", "zog um", "ist umgezogen"],
      ["wachsen", "wuchs", "ist gewachsen", "steigen", "stieg", "ist gestiegen"],
      ["essen", "aß", "hat gegessen", "trinken", "trank", "hat getrunken"],
      ["sprechen", "sprach", "hat gesprochen", "lesen", "las", "hat gelesen"],
      ["sehen", "sah", "hat gesehen", "schreiben", "schrieb", "hat geschrieben"],
      ["nehmen", "nahm", "hat genommen", "geben", "gab", "hat gegeben"],
      ["finden", "fand", "hat gefunden", "helfen", "half", "hat geholfen"],
      ["treffen", "traf", "hat getroffen", "schlafen", "schlief", "hat geschlafen"],
      ["stehen", "stand", "hat gestanden", "sitzen", "saß", "hat gesessen"],
      ["liegen", "lag", "hat gelegen", "tun", "tat", "hat getan"],
      ["bringen", "brachte", "hat gebracht", "denken", "dachte", "hat gedacht"],
      ["wissen", "wusste", "hat gewusst", "kennen", "kannte", "hat gekannt"],
      ["verstehen", "verstand", "hat verstanden", "vergessen", "vergaß", "hat vergessen"],
      ["bekommen", "bekam", "hat bekommen", "beginnen", "begann", "hat begonnen"],
      ["anrufen", "rief an", "hat angerufen", "einladen", "lud ein", "hat eingeladen"],
      ["anfangen", "fing an", "hat angefangen", "ziehen", "zog", "hat gezogen"],
      ["tragen", "trug", "hat getragen", "waschen", "wusch", "hat gewaschen"],
      ["halten", "hielt", "hat gehalten", "fallen", "fiel", "ist gefallen"],
      ["heißen", "hieß", "hat geheißen", "rufen", "rief", "hat gerufen"],
      ["schließen", "schloss", "hat geschlossen", "verlieren", "verlor", "hat verloren"],
      ["gewinnen", "gewann", "hat gewonnen", "singen", "sang", "hat gesungen"],
      ["verlassen", "verließ", "hat verlassen", "empfehlen", "empfahl", "hat empfohlen"],
      ["schneiden", "schnitt", "hat geschnitten", "streiten", "stritt", "hat gestritten"],
      ["bitten", "bat", "hat gebeten", "beißen", "biss", "hat gebissen"],
    ], rh=False, full=True),
    T("Ablautreihen", ["Muster", "Verben"], [
      ["ei – ie – ie", "bleiben blieb geblieben · schreiben · steigen"],
      ["ei – i – i", "schneiden schnitt geschnitten · streiten · reiten"],
      ["i – a – u", "finden fand gefunden · singen · trinken · springen"],
      ["ie – o – o", "fliegen flog geflogen · verlieren · schließen"],
      ["e – a – o", "sprechen sprach gesprochen · helfen · nehmen · treffen"],
    ]),
    N(("!Wann fällt ge- weg?", "only two cases: -ieren verbs and unstressed prefixes (be- ge- er- ver- zer- ent- emp- miss-)"),
      ("Stellung", "haben/sein in position 2, participle at the very end — spoken past for almost everything")),
  ),
  B("ref-praeteritum", "Präteritum & Plusquamperfekt", "A2", "war · hatte · es gab · -te",
    T("sein · haben", ["", "sein", "haben"], [
      ["ich", "war", "hatte"], ["du", "warst", "hattest"], ["er/sie/es", "war", "hatte"],
      ["wir", "waren", "hatten"], ["ihr", "wart", "hattet"], ["sie/Sie", "waren", "hatten"],
    ]),
    T("Muster", ["", "machen\nregelmäßig", "gehen\nunregelmäßig", "bringen\nMischverb"], [
      ["ich", "mach**te**", "ging", "brachte"], ["du", "mach**test**", "gingst", "brachtest"],
      ["er/sie/es", "mach**te**", "ging", "brachte"], ["wir", "mach**ten**", "gingen", "brachten"],
      ["ihr", "mach**tet**", "gingt", "brachtet"], ["sie/Sie", "mach**ten**", "gingen", "brachten"],
    ]),
    T("Modalverben", ["", "können", "müssen", "wollen", "dürfen", "sollen", "mögen"], [
      ["ich / er", "konnte", "musste", "wollte", "durfte", "sollte", "mochte"],
      ["wir / sie", "konnten", "mussten", "wollten", "durften", "sollten", "mochten"],
    ]),
    N(("Gebrauch", "written past (stories, news). In speech only for `sein, haben, es gab` and modals: `Ich **musste** arbeiten.`"),
      ("ich = er", "in every Präteritum: `ich war / er war`"),
      ("Modalverben", "lose the umlaut: `können → konnte`"),
      ("Plusquamperfekt", "`hatte/war` + Partizip II, earlier of two past events: `Nachdem ich gegessen **hatte**, ging ich ins Bett.`")),
  ),
  B("ref-futur", "Futur & werden", "A2", "werden + Infinitiv",
    T("", ["Form", "Bildung", "Gebrauch", "Beispiel"], [
      ["Präsens + Zeitwort", "Präsens", "default for plans (9 of 10)", "Nächste Woche **fliege** ich nach Hause."],
      ["Futur I", "werden + Infinitiv", "prediction, promise, present assumption", "Er **wird** wohl im Büro **sein**."],
      ["Futur II", "werden + PII + haben/sein", "assumption about the past; rare", "Sie **wird** den Zug verpasst **haben**."],
    ], full=True),
    T("Die drei Jobs von werden", ["Job", "Beispiel"], [
      ["Vollverb _become_", "Ich werde Lehrer."],
      ["Futur", "Ich werde kommen."],
      ["Passiv", "Das Haus wird gebaut."],
    ]),
  ),
  B("ref-konjunktiv", "Konjunktiv II", "B1", "wäre · hätte · würde · könnte",
    T("", ["", "sein", "haben", "werden", "können", "müssen", "sollen", "dürfen"], [
      ["ich", "wäre", "hätte", "würde", "könnte", "müsste", "sollte", "dürfte"],
      ["du", "wär(e)st", "hättest", "würdest", "könntest", "müsstest", "solltest", "dürftest"],
      ["er/sie/es", "wäre", "hätte", "würde", "könnte", "müsste", "sollte", "dürfte"],
      ["wir", "wären", "hätten", "würden", "könnten", "müssten", "sollten", "dürften"],
      ["ihr", "wär(e)t", "hättet", "würdet", "könntet", "müsstet", "solltet", "dürftet"],
      ["sie/Sie", "wären", "hätten", "würden", "könnten", "müssten", "sollten", "dürften"],
    ], full=True),
    T("Einsätze", ["Funktion", "Beispiel"], [
      ["Höflichkeit", "Könnten Sie mir bitte helfen? · Ich hätte gern einen Kaffee."],
      ["Wunsch", "Ich wäre gern reicher. · Wenn ich doch mehr Zeit hätte!"],
      ["Irreal", "Wenn ich Zeit hätte, würde ich mitkommen."],
      ["Ratschlag", "Du solltest mehr schlafen. · An deiner Stelle würde ich …"],
      ["Vergangenheit", "Wenn ich Zeit **gehabt hätte**, **wäre** ich **gekommen**."],
    ]),
    N(("!Alle anderen Verben", "`würde + Infinitiv`: `Ich **würde** gern mehr **reisen**.` Real forms you'll still hear: `käme, ginge, gäbe, wüsste, fände, bräuchte`"),
      ("Vergangenheit", "only one form: `hätte / wäre + Partizip II` · `Ich hätte das nicht sagen sollen.`"),
      ("ohne wenn", "verb first: `**Hätte** ich Zeit, würde ich mitkommen.`")),
  ),
  B("ref-passiv", "Passiv", "B1", "werden + Partizip II · worden · sich lassen",
    T("", ["Zeit", "Bildung", "Beispiel"], [
      ["Präsens", "werden + PII", "Das Haus **wird** gebaut."],
      ["Präteritum", "wurde + PII", "Das Haus **wurde** gebaut."],
      ["Perfekt", "ist + PII + **worden**", "Das Haus **ist** gebaut **worden**."],
      ["mit Modalverb", "Modal + PII + werden", "Das Haus **muss** gebaut **werden**."],
      ["Zustandspassiv", "sein + PII", "Die Tür **ist** geöffnet. _(state)_"],
      ["Vorgangspassiv", "werden + PII", "Die Tür **wird** geöffnet. _(process)_"],
    ]),
    T("Wer war es?", ["Präp.", "für", "Beispiel"], [
      ["von + Dat", "Person / Agent", "Der Brief wurde **von meinem Chef** geschrieben."],
      ["durch + Akk", "Mittel / Ursache", "Die Stadt wurde **durch das Erdbeben** zerstört."],
    ]),
    T("Ersatzformen", ["Form", "Sinn", "Beispiel"], [
      ["sich lassen + Inf", "can be …ed", "Das Problem **lässt sich** leicht **lösen**."],
      ["sein + zu + Inf", "must/can be …ed", "Das Formular **ist** bis Freitag **abzugeben**."],
      ["man", "spoken default", "**Man** baut hier ein Haus."],
      ["-bar", "…able", "machbar, essbar, lesbar"],
    ]),
    N(("worden ≠ geworden", "passive perfect loses ge-: `ist gebaut **worden**` · `geworden` = became: `Er ist Arzt geworden.`"),
      ("es-Passiv", "no object: `**Es wird** hier viel gearbeitet.` → `Hier **wird** viel gearbeitet.`")),
  ),
  B("ref-imperativ", "Imperativ", "A1", "Komm! Kommt! Kommen Sie!",
    T("", ["", "kommen", "sprechen", "fahren", "arbeiten", "sein", "haben", "nehmen"], [
      ["du", "Komm!", "Sprich!", "Fahr!", "Arbeite!", "Sei!", "Hab!", "Nimm!"],
      ["ihr", "Kommt!", "Sprecht!", "Fahrt!", "Arbeitet!", "Seid!", "Habt!", "Nehmt!"],
      ["Sie", "Kommen Sie!", "Sprechen Sie!", "Fahren Sie!", "Arbeiten Sie!", "Seien Sie!", "Haben Sie!", "Nehmen Sie!"],
      ["wir", "Kommen wir!", "Sprechen wir!", "Fahren wir!", "Arbeiten wir!", "Seien wir!", "Haben wir!", "Nehmen wir!"],
    ], full=True),
    N(("!du-Form", "du-form − st − pronoun: `du kommst → Komm!` Keeps e→i (`Sprich!`), loses umlaut (`Fahr!`), -t/-d stems keep -e (`Arbeite! Warte!`)"),
      ("Präfix", "still goes to the end: `**Steh** bitte **auf**! **Ruf** mich **an**!`"),
      ("Weicher", "`bitte · mal · doch`: `Komm **doch mal** vorbei!` · politer: `**Könnten Sie** …? **Würdest du** …?`")),
  ),
  B("ref-reflexiv", "Reflexive & reziproke Verben", "B1", "mich/mir · sich · einander",
    T("", PERS, [
      ["Akkusativ", "mich", "dich", "sich", "uns", "euch", "sich"],
      ["Dativ", "mir", "dir", "sich", "uns", "euch", "sich"],
    ]),
    T("Verben", ["Typ", "Verben"], [
      ["echt (nur mit sich)", "sich beeilen · bedanken (bei/für) · verlieben (in) · befinden · erholen · schämen · irren · weigern"],
      ["unecht (manchmal)", "sich freuen (über/auf) · interessieren (für) · erinnern (an) · entschuldigen · waschen · anziehen · setzen · treffen · ärgern · verletzen"],
      ["reziprok", "sich kennenlernen · streiten · umarmen · verstehen · duzen → `einander`, `miteinander`, `voneinander`"],
    ], full=True),
    T("Wo steht sich?", ["Satz", "Beispiel"], [
      ["Hauptsatz, Nomen-Subjekt", "Gestern hat **sich** mein Bruder verletzt."],
      ["Nebensatz", "…, weil ich **mich** beeilen muss."],
      ["Frage", "Freust du **dich**?"],
    ]),
    N(("!Akk oder Dat?", "another Akk object present → reflexive goes Dativ: `Ich wasche **mich**` vs `Ich wasche **mir** die Hände`. Only mich/mir, dich/dir differ."),
      ("einander", "`Wir treffen **uns**` is ambiguous; `Wir treffen **einander**` isn't")),
  ),
  B("ref-verbpraep", "Verben mit Präposition · da- & wo-", "B1", "warten auf · darauf · worauf",
    T("", ["Kasus", "Verben"], [
      ["Akkusativ", "warten auf · sich freuen auf (Zukunft) / über (Vergangenheit) · denken an · sich erinnern an · glauben an · sich interessieren für · sich entscheiden für · sich kümmern um · bitten um · sprechen über · sich ärgern über · sich gewöhnen an · achten auf · verzichten auf"],
      ["Dativ", "sprechen mit · anfangen mit · aufhören mit · sich treffen mit · rechnen mit · sich beschäftigen mit · abhängen von · träumen von · erzählen von · gehören zu · einladen zu · Angst haben vor · sich fürchten vor · leiden unter · teilnehmen an"],
    ], full=True),
    T("da- / wo-Wörter", ["Präp.", "da- (Aussage)", "wo- (Frage)"], [
      ["auf", "darauf", "worauf"], ["an", "daran", "woran"], ["über", "darüber", "worüber"],
      ["um", "darum", "worum"], ["mit", "damit", "womit"], ["von", "davon", "wovon"],
      ["für", "dafür", "wofür"], ["vor", "davor", "wovor"], ["zu", "dazu", "wozu"], ["nach", "danach", "wonach"],
    ]),
    N(("!Sache vs Person", "thing → `da-`: `Ich warte **darauf**.` · person → pronoun: `Ich warte **auf ihn**.`"),
      ("-r-", "before a vowel: `da**r**auf, wo**r**an`"),
      ("Brücke zum Nebensatz", "`Ich freue mich **darauf**, dass du kommst.` · `Es hängt **davon** ab, ob …`")),
  ),
  B("ref-lassen", "lassen & Nomen-Verb-Verbindungen", "B1", "machen lassen · eine Frage stellen",
    T("lassen", ["Bedeutung", "Beispiel"], [
      ["have sth done", "Ich **lasse** mein Auto reparieren."],
      ["let / allow", "Meine Eltern **lassen** mich nicht ausgehen."],
      ["leave behind", "Ich habe meinen Schlüssel zu Hause **gelassen**."],
      ["sich lassen = can be done", "Das **lässt sich** machen."],
    ]),
    T("lassen + Vorsilbe", ["Verb", "Bedeutung", "Verb", "Bedeutung"], [
      ["verlassen", "leave (a place/person)", "zulassen", "permit"],
      ["entlassen", "dismiss", "hinterlassen", "leave behind"],
      ["überlassen", "leave sth to sb", "loslassen", "let go"],
      ["nachlassen", "ease off", "weglassen", "omit"],
    ], rh=False),
    T("Nomen-Verb-Verbindungen", ["Verbindung", "Bedeutung", "Verbindung", "Bedeutung"], [
      ["eine Entscheidung treffen", "decide", "Angst haben", "be afraid"],
      ["eine Frage stellen", "ask", "Hilfe leisten", "help"],
      ["in Kontakt treten", "get in touch", "zur Verfügung stehen", "be available"],
      ["Rücksicht nehmen (auf)", "be considerate", "eine Rolle spielen", "matter"],
      ["in Frage kommen", "be an option", "Bescheid sagen / wissen", "let know / know"],
      ["Abschied nehmen", "say goodbye", "einen Antrag stellen", "file an application"],
    ], rh=False),
    N(("Perfekt-Falle", "with a 2nd verb: double infinitive — `Ich habe mein Auto reparieren **lassen**` (not gelassen). Same for modals: `Ich habe arbeiten **müssen**.`")),
  ),
]))

# ─────────────────────────── Adjektive & Deklination
SECTIONS.append(("sec-adjektive", "Adjektive & Deklination", [
  B("ref-allinone", "All-in-One Deklination (Laura)", "A2", "stark / schwach · 4 Muster · ein Chart für alles",
    T("Endungen: stark / schwach", G4, [
      ["Nominativ", "-r / -e", "-e / -e", "-s / -e", "-e / -e"],
      ["Akkusativ", "-n / -e", "-e / -e", "-s / -e", "-e / -e"],
      ["Dativ", "-m / -n", "-r / -n", "-m / -n", "-n / -n"],
      ["Genitiv", "-s / -n", "-r / -n", "-s / -n", "-r / -n"],
    ], gc=True),
    T("Die 4 Muster", ["#", "Aufbau", "Regel"], [
      ["1", "Artikelwort + Adjektiv", "Artikel **stark**, Adjektiv **schwach** (default)"],
      ["2", "ein-Wort in 3 Ausnahme-Spots + Adj.", "Artikel **ohne Endung**, Adjektiv **stark**"],
      ["3", "nur Adjektiv", "Adjektiv **stark**"],
      ["4", "Regelbrecher-Plural + Adj.", "beide **stark**"],
    ]),
    T("Sonderwörter", ["Gruppe", "Wörter", "Folge"], [
      ["3 Ausnahme-Spots", "ein kein irgendein + Possessiva in m Nom · n Nom · n Akk", "Artikel ohne Endung → Adjektiv stark"],
      ["Null-Wörter", "ein bisschen · etwas · nichts · genug · lauter · ein paar", "nie Endung → Adjektiv stark: `etwas heißes Wasser`"],
      ["Regelbrecher (Pl.)", "etlich- verschieden- zahlreich- folgend- manch- wenig- ander- einig- mehrer- viel-", "beide stark: `viele große Hunde`"],
    ], full=True),
    N(("So geht's", "1 Genus (Spalte) → 2 Kasus (Zeile) → 3 Muster wählen → 4 Endung anhängen, meist mit Füll-e vor Konsonant: `dies + r → dieser`, `mein + m → meinem`; kein Füll-e vor -e: `diese`"),
      ("Beispiel", "`dies**er** rot**e** Apfel` · `dies**en** rot**en** Apfel` · `dies**em** rot**en** Apfel` · `dies**es** rot**en** Apfels`")),
  ),
  B("ref-adjendungen", "Adjektivendungen", "A2", "der gute · ein guter · guter",
    T("nach der-Wörtern (der dieser jeder welcher alle)", G4, [
      ["Nominativ", "der gut**e** Wein", "die gut**e** Suppe", "das gut**e** Bier", "die gut**en** Weine"],
      ["Akkusativ", "den gut**en** Wein", "die gut**e** Suppe", "das gut**e** Bier", "die gut**en** Weine"],
      ["Dativ", "dem gut**en** Wein", "der gut**en** Suppe", "dem gut**en** Bier", "den gut**en** Weinen"],
      ["Genitiv", "des gut**en** Weines", "der gut**en** Suppe", "des gut**en** Bieres", "der gut**en** Weine"],
    ], full=True),
    T("nach ein-Wörtern (ein kein mein unser)", G4, [
      ["Nominativ", "ein gut**er** Wein", "eine gut**e** Suppe", "ein gut**es** Bier", "keine gut**en** Weine"],
      ["Akkusativ", "einen gut**en** Wein", "eine gut**e** Suppe", "ein gut**es** Bier", "keine gut**en** Weine"],
      ["Dativ", "einem gut**en** Wein", "einer gut**en** Suppe", "einem gut**en** Bier", "keinen gut**en** Weinen"],
      ["Genitiv", "eines gut**en** Weines", "einer gut**en** Suppe", "eines gut**en** Bieres", "keiner gut**en** Weine"],
    ], full=True),
    T("ohne Artikel", G4, [
      ["Nominativ", "gut**er** Wein", "gut**e** Suppe", "gut**es** Bier", "gut**e** Weine"],
      ["Akkusativ", "gut**en** Wein", "gut**e** Suppe", "gut**es** Bier", "gut**e** Weine"],
      ["Dativ", "gut**em** Wein", "gut**er** Suppe", "gut**em** Bier", "gut**en** Weinen"],
      ["Genitiv", "gut**en** Weines", "gut**er** Suppe", "gut**en** Bieres", "gut**er** Weine"],
    ], full=True),
    N(("Nach dem Verb", "no ending: `Das Auto ist **neu**.` — endings only before a noun: `das **neue** Auto`"),
      ("!Ein-Signal-Regel", "article shows gender/case → adjective -e/-en · article silent (ein m Nom, n Nom/Akk) → adjective takes it: `ein gut**er**, ein gut**es**` · no article → full der-ending"),
      ("der-Tabelle", "only 5 cells -e (3× Nom Sg + f/n Akk), all others -en"),
      ("ein-Tabelle", "= der-table except 3 cells: `ein gut**er**`, `ein gut**es**` (×2)"),
      ("ohne Artikel", "= der/die/das endings minus d-, except Gen m/n `-en` (`gut**en** Weines`)"),
      ("Sonderfälle", "`hoch → hoher` · `dunkel → dunkles` · `teuer → teures` · city -er never changes: `der Münchner Flughafen`")),
  ),
  B("ref-adjplural", "Adjektive: Singular → Plural", "A2", "dieselbe Phrase, beide Zahlen",
    T("", ["", "m:der gute Wein", "p:Plural", "m:mein guter Freund", "p:Plural", "m:guter Wein", "p:Plural"], [
      ["Nominativ", "der gut**e** Wein", "die gut**en** Weine", "mein gut**er** Freund", "meine gut**en** Freunde", "gut**er** Wein", "gut**e** Weine"],
      ["Akkusativ", "den gut**en** Wein", "die gut**en** Weine", "meinen gut**en** Freund", "meine gut**en** Freunde", "gut**en** Wein", "gut**e** Weine"],
      ["Dativ", "dem gut**en** Wein", "den gut**en** Wein**en**", "meinem gut**en** Freund", "meinen gut**en** Freunde**n**", "gut**em** Wein", "gut**en** Wein**en**"],
      ["Genitiv", "des gut**en** Wein**es**", "der gut**en** Weine", "meines gut**en** Freund**es**", "meiner gut**en** Freunde", "gut**en** Wein**es**", "gut**er** Weine"],
    ], full=True),
    T("3 Genera → 1 Plural", ["Singular", "Plural Nom", "Plural Dat"], [
      ["{m:der alt**e** Mann}", "die alt**en** Männer", "den alt**en** Männer**n**"],
      ["{f:die klein**e** Stadt}", "die klein**en** Städte", "den klein**en** Städte**n**"],
      ["{n:das neu**e** Haus}", "die neu**en** Häuser", "den neu**en** Häuser**n**"],
      ["{m:ein alt**er** Mann}", "alt**e** Männer", "alt**en** Männer**n**"],
      ["{n:ein neu**es** Haus}", "neu**e** Häuser", "neu**en** Häuser**n**"],
    ], rh=False),
    N(("!Plural mit Artikelwort", "`die, diese, alle, meine, keine` + plural → always **-en**. Only the article-less plural varies: `gut**e** · gut**e** · gut**en** · gut**er**`"),
      ("!Mehrere Adjektive", "same ending each: `ein gut**er**, alt**er** Wein` · `mit frisch**em**, kalt**em** Wasser`"),
      ("Nomen-Endungen", "Dat Pl `-n` and Gen m/n `-(e)s` belong to the noun: `mit den gut**en** Wein**en**`")),
  ),
  B("ref-komparativ", "Komparativ & Superlativ", "A2", "als · wie · am …sten",
    T("", ["Positiv", "Komparativ", "Superlativ", "vor Nomen"], [
      ["schnell", "schnell**er**", "am schnell**sten**", "der schnell**ste**"],
      ["alt", "**ä**lter", "am ältesten", "der älteste"],
      ["groß", "größer", "am größten", "der größte"],
      ["teuer", "teurer", "am teuersten", "der teuerste"],
      ["gut", "{f:besser}", "{f:am besten}", "{f:der beste}"],
      ["viel", "{f:mehr}", "{f:am meisten}", "{f:der meiste}"],
      ["gern", "{f:lieber}", "{f:am liebsten}", "—"],
      ["hoch", "{f:höher}", "{f:am höchsten}", "{f:der höchste}"],
      ["nah", "{f:näher}", "{f:am nächsten}", "{f:der nächste}"],
    ]),
    T("Vergleichen", ["Muster", "Beispiel"], [
      ["Komparativ + als", "Er ist größ**er als** ich."],
      ["(genau)so … wie", "Er ist **so** groß **wie** ich."],
      ["nicht so … wie", "Heute ist es **nicht so** kalt **wie** gestern."],
      ["immer + Komparativ", "Es wird **immer kälter**."],
      ["je … desto", "**Je** mehr ich lerne, **desto** besser verstehe ich."],
    ]),
    N(("Umlaut", "1-syllable a/o/u: `alt älter, groß größer, jung jünger, lang länger, warm wärmer, kurz kürzer, stark stärker, klug klüger`"),
      ("-esten", "after -d -t -s -ß -z: `am ält**e**sten, am heiß**e**sten` — not -isch/-end: `am typischsten`"),
      ("!als oder wie?", "difference → `als` · equality → `so … wie`. `größer wie` is wrong."),
      ("Stellung", "before noun = normal adjective: `mit dem schnellsten Zug` · after verb: `am schnellsten`")),
  ),
  B("ref-adjmengen", "Adjektive nach Mengenwörtern & als Nomen", "B1", "viele gute · alle guten · etwas Neues · der Deutsche",
    T("Welche Tabelle?", ["Mengenwort", "Adjektiv wie …", "Beispiele"], [
      ["alle · beide · sämtliche · solche · manche · welche · diese", "nach der → **-en**", "alle gut**en** Freunde · beide neu**en** Autos"],
      ["viele · wenige · einige · mehrere · andere · ein paar · Zahlen", "ohne Artikel", "viele gut**e** Freunde · zwei klein**e** Kinder · trotz einiger gut**er** Ideen"],
      ["viel · wenig (Singular)", "ohne Artikel", "viel frisch**es** Obst · mit wenig heiß**em** Wasser"],
    ], full=True),
    T("etwas Neues", ["Nom / Akk", "Dativ", "Bedeutung"], [
      ["etwas Neu**es**", "mit etwas Neu**em**", "something new"],
      ["nichts Gut**es**", "von nichts Gut**em**", "nothing good"],
      ["viel Interessant**es**", "mit viel Interessant**em**", "lots of interesting things"],
      ["alles Gut**e**", "von allem Gut**en**", "all the best"],
    ], rh=False),
    T("Adjektiv als Nomen", ["", "mit der", "mit ein", "Plural"], [
      ["Nominativ", "der Deutsch**e**", "ein Deutsch**er**", "die Deutsch**en** / viele Deutsch**e**"],
      ["Akkusativ", "den Deutsch**en**", "einen Deutsch**en**", "die Deutsch**en** / viele Deutsch**e**"],
      ["Dativ", "dem Deutsch**en**", "einem Deutsch**en**", "den Deutsch**en** / vielen Deutsch**en**"],
      ["Genitiv", "des Deutsch**en**", "eines Deutsch**en**", "der Deutsch**en** / vieler Deutsch**er**"],
    ]),
    N(("!alle vs viele", "`alle` acts like die → `alle gut**en** Freunde` · `viele` is just an adjective → `viele gut**e** Freunde`"),
      ("manche / solche", "both heard in plural; -en is the safe default"),
      ("Als Nomen", "`der/die Bekannte, Angestellte, Verwandte, Erwachsene, Jugendliche, Kranke, Reisende` · `Ich bin Deutsch**er**` vs `den Deutsch**en**`"),
      ("Unveränderlich", "`rosa lila beige orange prima super klasse extra` + city -er: `eine rosa Bluse`"),
      ("Komparativ + Endung", "`ein schneller**er** Zug · ein besser**es** Angebot · die älter**en** Kinder`")),
  ),
  B("ref-adverbien", "Adverbien & Partikeln", "A2", "oft · gern · leider · doch · mal",
    T("Häufigkeit", ["100 %", "", "", "", "", "", "0 %"], [
      ["immer", "meistens", "oft", "manchmal", "selten", "fast nie", "nie"],
    ], rh=False),
    T("Wortgruppen", ["Gruppe", "Wörter"], [
      ["Gewohnheit (-s)", "montags · abends · morgens · wochentags — `**Montags** gehe ich schwimmen.`"],
      ["Reihenfolge", "zuerst → dann → danach → später → schließlich / am Ende"],
      ["Satzadverbien", "leider · hoffentlich · vielleicht · wahrscheinlich · natürlich · eigentlich · übrigens · trotzdem · deshalb · sicher · bestimmt · zum Glück"],
    ], full=True),
    T("Modalpartikeln", ["Partikel", "Funktion", "Beispiel"], [
      ["doch", "contradiction / encouragement", "Komm **doch** mit!"],
      ["mal", "softens", "Kannst du **mal** helfen?"],
      ["ja", "shared knowledge / surprise", "Das ist **ja** toll!"],
      ["denn", "curiosity in questions", "Was machst du **denn**?"],
      ["eigentlich", "actually, by the way", "Wie heißt du **eigentlich**?"],
      ["halt / eben", "that's just how it is", "Das ist **halt** so."],
    ]),
    N(("!gern", "right after verb + pronouns: `Ich trinke **gern** Kaffee.` · with modal before infinitive: `Ich möchte **gern** mitkommen.`"),
      ("Position 1", "zuerst/dann/… count as Pos 1: `Dann **gehe ich**` — never `Dann ich gehe`"),
      ("Adverb = Adjektiv", "no -ly: `Er ist schnell` / `Er läuft schnell`")),
  ),
  B("ref-partizip", "Partizip I & II als Adjektiv", "B1", "weinend · gekocht",
    T("", ["Form", "Bildung", "Sinn", "Beispiele"], [
      ["Partizip I", "Infinitiv + -d + Endung", "active, simultaneous — noun **does** it", "das weinen**d**e Kind · ein spannen**d**er Film · steigen**d**e Preise"],
      ["Partizip II", "PII + Endung", "passive, finished — noun **has it done**", "das gekocht**e** Essen · ein geschrieben**er** Brief · gebraten**e** Kartoffeln"],
      ["zu + Partizip I", "zu + Inf + -d + Endung", "must / can be done", "die **zu lösende** Aufgabe"],
    ], full=True),
    N(("Erweitertes Partizip", "`der **gestern von meinem Kollegen geschriebene** Brief` = `der Brief, der gestern … geschrieben wurde` — recognise it in reading")),
  ),
]))

# ─────────────────────────── Satzbau
SECTIONS.append(("sec-satzbau", "Satzbau", [
  B("ref-algorithmus", "Satzbau-Algorithmus & Satzklammer", "A1", "Position 2 · TeKaMoLo",
    T("Sieben Schritte", ["#", "Schritt", "Regel"], [
      ["1", "Satztyp", "Aussage · W-Frage · Ja/Nein-Frage · Imperativ · Nebensatz"],
      ["2", "Verb platzieren", "Pos 2: Aussage, W-Frage · Pos 1: Ja/Nein, Imperativ · Ende: Nebensatz"],
      ["3", "2. Verbteil ans Ende", "Infinitiv, Partizip II, Präfix → closes the bracket"],
      ["4", "Position 1 = ein Element", "usually subject; fronting anything else puts the subject right after the verb"],
      ["5", "Mittelfeld", "pronouns first, then **Te**mporal → **Ka**usal → **Mo**dal → **Lo**kal"],
      ["6", "Zwei Objekte", "Nomen+Nomen: Dat→Akk · Pron+Pron: Akk→Dat · gemischt: Pronomen zuerst"],
      ["7", "nicht", "late — but before the closing bracket, a predicate adjective, or a prepositional phrase"],
    ], full=True),
    T("Satzklammer", ["Position 1", "Verb (Pos 2)", "Mittelfeld", "Satzende"], [
      ["Ich", "**muss**", "morgen früh", "**aufstehen.**"],
      ["Morgen", "**stehe**", "ich früh", "**auf.**"],
      ["Gestern", "**habe**", "ich viel", "**gearbeitet.**"],
      ["Das Haus", "**wird**", "seit Mai", "**gebaut.**"],
      ["Wann", "**bist**", "du nach München", "**gekommen?**"],
      ["—", "**Kannst**", "du mir das", "**erklären?**"],
    ], rh=False),
    T("TeKaMoLo", ["Te — wann?", "Ka — warum?", "Mo — wie?", "Lo — wo/wohin?"], [
      ["morgen", "wegen der Arbeit", "mit dem Zug", "nach Berlin"],
      ["heute", "wegen des Regens", "mit dem Auto", "zur Arbeit"],
    ], rh=False),
    N(("Beispiel", "`Ich fahre morgen wegen der Arbeit mit dem Zug nach Berlin.`"),
      ("Position 0", "`und aber oder denn sondern` don't count: `…, **denn** ich bin müde.`"),
      ("!Elemente, nicht Wörter", "`**Der große Hund mit dem roten Halsband** schläft …` — 7 words, still Pos 1")),
  ),
  B("ref-konjunktionen", "Konjunktionen", "A2", "Position 0 · Verb ans Ende · Position 1",
    T("", ["Gruppe", "Wort", "Bedeutung", "Beispiel"], [
      ["0 · ADUSO", "und", "and", "Ich lerne Deutsch **und** ich arbeite in München."],
      ["0 · ADUSO", "aber", "but", "Der Kurs ist schwer, **aber** er macht Spaß."],
      ["0 · ADUSO", "denn", "because", "Ich bleibe zu Hause, **denn** ich bin müde."],
      ["0 · ADUSO", "sondern", "but rather (after negation)", "Nicht heute, **sondern** morgen."],
      ["0 · ADUSO", "oder", "or", "Wir gehen ins Kino **oder** wir bleiben zu Hause."],
      ["Ende", "weil", "because", "…, **weil** ich müde **bin**."],
      ["Ende", "dass", "that", "Ich weiß, **dass** du recht **hast**."],
      ["Ende", "wenn", "if / whenever", "Ruf an, **wenn** du Zeit **hast**."],
      ["Ende", "als", "when (one past event)", "**Als** ich klein **war**, …"],
      ["Ende", "ob", "whether", "Ich weiß nicht, **ob** er **kommt**."],
      ["Ende", "obwohl", "although", "…, **obwohl** es **regnet**."],
      ["Ende", "damit", "so that", "…, **damit** ich die Prüfung **bestehe**."],
      ["Ende", "bevor · nachdem", "before · after", "**Bevor** ich **gehe**, trinke ich Kaffee."],
      ["Ende", "während · bis · seit(dem)", "while · until · since", "**Während** ich **koche**, hört sie Musik."],
      ["Ende", "da", "since (formal because)", "**Da** es spät **ist**, gehe ich."],
      ["Ende", "falls", "in case", "**Falls** es **regnet**, bleiben wir hier."],
      ["Ende", "indem", "by …ing", "…, **indem** man viel **spricht**."],
      ["1 · Adverb", "deshalb · deswegen · darum", "therefore", "**Deshalb bleibe ich** zu Hause."],
      ["1 · Adverb", "trotzdem", "nevertheless", "**Trotzdem gehe ich** raus."],
      ["1 · Adverb", "außerdem", "besides", "**Außerdem habe ich** keine Zeit."],
      ["1 · Adverb", "danach · dann", "afterwards", "**Danach gehe ich** einkaufen."],
      ["1 · Adverb", "sonst", "otherwise", "Beeil dich, **sonst kommen wir** zu spät."],
    ], full=True),
    N(("!Drei Bauweisen", "`…, **denn** ich **bin** müde.` (0) · `…, **weil** ich müde **bin**.` (Ende) · `Ich bin müde. **Deshalb bleibe** ich …` (1)"),
      ("aber / sondern", "`sondern` only corrects a negation: `**kein** Tee, **sondern** Kaffee`"),
      ("als / wenn / wann", "`als` one past event · `wenn` repeated or present/future · `wann` questions only")),
  ),
  B("ref-nebensatz", "Nebensätze & Infinitivsätze", "B1", "Verb am Ende · zu · um … zu · damit",
    T("Finalsätze & Co.", ["Konstruktion", "wann", "Beispiel"], [
      ["um … zu", "purpose, same subject", "Ich lerne Deutsch, **um** in München **zu arbeiten**."],
      ["damit", "purpose, different subject", "Ich erkläre es, **damit** du es **verstehst**."],
      ["ohne … zu", "without, same subject", "Er ging, **ohne** etwas **zu sagen**."],
      ["ohne dass", "without, different subject", "Er ging, **ohne dass** ich es **merkte**."],
      ["(an)statt … zu", "instead of", "…, **statt** ins Kino **zu gehen**."],
      ["indem", "by doing", "Man spart, **indem** man weniger **ausgeht**."],
      ["brauchen + zu", "only with nicht/nur/kein", "Du **brauchst** nicht **zu kommen**."],
    ], full=True),
    T("Infinitiv mit zu", ["", "Beispiel"], [
      ["Trigger", "vorhaben · versuchen · vergessen · anfangen · aufhören · hoffen · beschließen · Lust/Zeit haben · es ist wichtig/schön/möglich"],
      ["Satz", "Ich habe vor, nach Berlin **zu ziehen**. · Ich habe vergessen, dich **anzurufen**."],
      ["kein zu", "after modals, lassen, gehen, sehen, hören, bleiben"],
    ], full=True),
    N(("Grundregel", "Konjunktion → Subjekt → … → **konjugiertes Verb zuletzt**: `…, dass du das Auto **gekauft hast**.`"),
      ("!Verb, Komma, Verb", "Nebensatz first = Pos 1: `Weil ich müde **bin**, **gehe** ich ins Bett.`"),
      ("!um … zu oder damit?", "one subject → `um … zu` · two subjects → `damit`"),
      ("Indirekte Frage", "`Wo wohnst du? → Ich weiß nicht, **wo** du **wohnst**.` · `Kommt er? → Ich frage, **ob** er **kommt**.`")),
  ),
  B("ref-relativ", "Relativsätze", "B1", "der · die · das · denen · dessen · deren",
    T("", G4, [
      ["Nominativ", "der", "die", "das", "die"],
      ["Akkusativ", "den", "die", "das", "die"],
      ["Dativ", "dem", "der", "dem", "**denen**"],
      ["Genitiv", "**dessen**", "**deren**", "**dessen**", "**deren**"],
    ], gc=True),
    T("Beispiele", ["Kasus", "Satz"], [
      ["Nominativ", "Der Mann, **der** dort steht, ist mein Chef."],
      ["Akkusativ", "Der Mann, **den** ich getroffen habe, …"],
      ["Dativ", "Der Mann, **dem** ich geholfen habe, …"],
      ["Genitiv", "Der Mann, **dessen** Auto kaputt ist, …"],
      ["Präp + Dat", "Die Kollegen, **mit denen** ich arbeite, …"],
    ]),
    N(("Zwei Fragen", "gender/number ← the noun it refers to · case ← its job inside the relative clause"),
      ("Merke", "= definite article except 5 cells: `denen`, `dessen deren dessen deren`"),
      ("Präposition zuerst", "`die Firma, **bei der** ich arbeite` — never stranded at the end"),
      ("was / wo", "`was` after alles/nichts/etwas/das or a whole clause: `Das ist alles, **was** ich weiß.` · `wo` for places: `die Stadt, **wo** ich wohne`")),
  ),
  B("ref-fragen", "Fragen & W-Wörter", "A1", "wer wen wem wessen · wo wohin woher",
    T("", ["W-Wort", "fragt nach", "Beispiel"], [
      ["{nom:wer}", "Person — Nom", "Wer wohnt hier?"],
      ["{akk:wen}", "Person — Akk", "Wen triffst du?"],
      ["{dat:wem}", "Person — Dat", "Wem hilfst du?"],
      ["{gen:wessen}", "Person — Gen", "Wessen Auto ist das?"],
      ["was", "Sache", "Was machst du?"],
      ["wo", "Ort — Position", "Wo wohnst du?"],
      ["wohin", "Ort — Richtung", "Wohin gehst du?"],
      ["woher", "Herkunft", "Woher kommst du?"],
      ["wann", "Zeitpunkt", "Wann fängt der Kurs an?"],
      ["seit wann / bis wann", "Anfang / Ende", "Seit wann lernst du Deutsch?"],
      ["wie lange", "Dauer", "Wie lange dauert der Kurs?"],
      ["wie oft", "Häufigkeit", "Wie oft gehst du ins Kino?"],
      ["wie", "Art und Weise", "Wie kommst du zur Arbeit?"],
      ["wie viel / wie viele", "Menge (unzählbar / zählbar)", "Wie viel kostet das? Wie viele Kinder hast du?"],
      ["warum / wieso / weshalb", "Grund", "Warum lernst du Deutsch?"],
      ["wozu", "Zweck", "Wozu brauchst du das?"],
      ["welch-", "Auswahl", "Welchen Kurs machst du?"],
      ["was für ein-", "Art", "Was für eine Wohnung suchst du?"],
    ]),
    N(("Ja/Nein-Frage", "verb first: `Kommst du morgen? Hast du Zeit?`"),
      ("doch", "yes to a negative question: `— Kommst du nicht mit? — **Doch**!`"),
      ("!welch- / was für", "`welch-` = which of a known set · `was für ein-` = what kind")),
  ),
  B("ref-negation", "Negation", "A1", "nicht vs kein · wo steht nicht",
    T("nicht oder kein?", ["Wort", "negiert", "Beispiel"], [
      ["kein-", "noun with ein or no article", "Ich habe **keine** Zeit."],
      ["nicht", "everything else (verbs, adjectives, der/possessive nouns)", "Das ist **nicht** mein Auto."],
    ]),
    T("Wo steht nicht?", ["Fall", "Beispiel"], [
      ["Standard: Ende", "Ich verstehe das **nicht**."],
      ["vor Satzklammer", "Ich rufe dich heute **nicht** an."],
      ["vor Adjektiv", "Der Film war **nicht** gut."],
      ["vor Präp-Phrase", "Ich fahre **nicht** nach Berlin."],
      ["vor dem Wort", "Ich fahre **nicht heute**, sondern morgen."],
    ]),
    T("Weitere", ["Wort", "Bedeutung", "Wort", "Bedeutung"], [
      ["nie / niemals", "never", "niemand", "nobody"],
      ["nichts", "nothing", "nirgendwo", "nowhere"],
      ["noch nicht", "not yet", "nicht mehr", "not any more"],
      ["kein … mehr", "no more …", "weder … noch", "neither … nor"],
    ], rh=False),
    N(("!Test", "could it take `ein` or nothing? → `kein` · has der/possessive? → `nicht`"),
      ("Keine doppelte", "`Ich habe **nichts** gesehen` — never `nicht nichts`")),
  ),
]))

# ─────────────────────────── Präpositionen
SECTIONS.append(("sec-praep", "Präpositionen", [
  B("ref-praepkasus", "Präpositionen & Kasus", "A1", "Akk · Dat · Wechsel · Gen",
    T("", ["Kasus", "Präpositionen", "Merkhilfe", "Beispiel"], [
      ["Akkusativ", "durch · für · gegen · ohne · um (+ bis, entlang)", "DOGFU", "Das ist **für meinen** Bruder."],
      ["Dativ", "aus · außer · bei · mit · nach · seit · von · zu (+ gegenüber, ab)", "aus-außer-bei-mit-nach-seit-von-zu", "Ich fahre **mit dem** Bus."],
      ["Wechsel", "in · an · auf · unter · über · vor · hinter · neben · zwischen", "wo → Dat · wohin → Akk", "in **der** / in **die** Küche"],
      ["Genitiv", "wegen · trotz · während · statt · außerhalb · innerhalb", "→ [Genitivpräpositionen](#ref-genitivpraep)", "**wegen des** Wetters"],
    ], full=True),
    T("Wechselpräpositionen", ["Präp.", "Wo? → Dativ", "Wohin? → Akkusativ"], [
      ["in", "Ich bin **in der** Küche.", "Ich gehe **in die** Küche."],
      ["auf", "Das Buch liegt **auf dem** Tisch.", "Ich lege es **auf den** Tisch."],
      ["an", "Das Bild hängt **an der** Wand.", "Ich hänge es **an die** Wand."],
      ["unter", "Die Katze schläft **unter dem** Bett.", "Sie geht **unter das** Bett."],
      ["über", "Die Lampe hängt **über dem** Tisch.", "Ich hänge sie **über den** Tisch."],
      ["vor", "Ich warte **vor dem** Haus.", "Ich stelle mich **vor das** Haus."],
      ["hinter", "Der Garten ist **hinter dem** Haus.", "Ich gehe **hinter das** Haus."],
      ["neben", "Er sitzt **neben mir**.", "Er setzt sich **neben mich**."],
      ["zwischen", "Es steht **zwischen den** Häusern.", "Ich stelle es **zwischen die** Häuser."],
    ]),
    T("Verbpaare", ["Wohin? (Akk, regelmäßig)", "Wo? (Dat, unregelmäßig)"], [
      ["stellen", "stehen"], ["legen", "liegen"], ["setzen", "sitzen"], ["hängen", "hängen"], ["stecken", "stecken"],
    ], rh=False),
    N(("!Das Verb verrät's", "`Ich **stelle** das Glas **auf den** Tisch.` → `Das Glas **steht auf dem** Tisch.`"),
      ("bis", "usually hands over to a 2nd preposition: `bis **zum** Bahnhof` · `bis **in die** Nacht` · `bis nächsten Montag`")),
  ),
  B("ref-wohin", "Wohin? — in · nach · zu · auf · an", "A1", "ins Kino · nach München · zum Arzt",
    T("Die Leiter — erste passende Zeile", ["#", "Ziel", "Präp.", "Beispiele"], [
      ["1", "Stadt · Land ohne Artikel · Kontinent · Richtung · Hause", "nach", "nach München · nach Italien · nach links · nach Hause"],
      ["2", "Person · Ort, zu dem man hingeht", "zu + Dat", "zum Arzt · zu Anna · zur Arbeit · zum Bahnhof"],
      ["3", "hinein", "in + Akk", "ins Kino · in die Küche · in die Schweiz · in die Berge"],
      ["4", "offene Fläche · Amt · Event", "auf + Akk", "auf den Markt · auf die Post · auf eine Party · aufs Land"],
      ["5", "Rand · Fläche · Wasser", "an + Akk", "ans Meer · an den See · ans Fenster"],
    ], full=True),
    T("Ein Ort, drei Fragen", ["Ort", "Wohin?", "Wo?", "Woher?"], [
      ["Kino", "ins Kino", "im Kino", "aus dem Kino"],
      ["Supermarkt", "in den Supermarkt", "im Supermarkt", "aus dem Supermarkt"],
      ["Arzt", "zum Arzt", "beim Arzt", "vom Arzt"],
      ["Anna", "zu Anna", "bei Anna", "von Anna"],
      ["Arbeit", "zur Arbeit", "auf der Arbeit", "von der Arbeit"],
      ["Schule", "in die / zur Schule", "in der Schule", "aus der Schule"],
      ["Uni", "zur / in die Uni", "an der / in der Uni", "von der Uni"],
      ["Post · Bank", "auf die / zur Post", "auf der Post", "von der Post"],
      ["Markt", "auf den Markt", "auf dem Markt", "vom Markt"],
      ["Party", "auf eine / zur Party", "auf einer Party", "von der Party"],
      ["Toilette", "auf die Toilette", "auf der Toilette", "von der Toilette"],
      ["Bahnhof", "zum Bahnhof", "am Bahnhof", "vom Bahnhof"],
      ["Stadt", "in die Stadt", "in der Stadt", "aus der Stadt"],
      ["München", "nach München", "in München", "aus München"],
      ["die Schweiz", "in die Schweiz", "in der Schweiz", "aus der Schweiz"],
      ["Mallorca", "nach Mallorca", "auf Mallorca", "von Mallorca"],
      ["Meer · See", "ans Meer · an den See", "am Meer · am See", "vom Meer"],
      ["Berge", "in die Berge", "in den Bergen", "aus den Bergen"],
      ["Land", "aufs Land", "auf dem Land", "vom Land"],
      ["Urlaub", "in den Urlaub", "im Urlaub", "aus dem Urlaub"],
      ["Bett", "ins Bett", "im Bett", "aus dem Bett"],
      ["Hause", "nach Hause", "zu Hause", "von zu Hause"],
    ]),
    N(("!Nur in/auf/an wechseln", "`nach zu aus von bei` are always Dativ. Only `in auf an` switch: go → Akk, be → Dat."),
      ("!aus oder von?", "Wo with `in` → Woher `aus` (`im Kino → aus dem Kino`) · Wo with `an/auf/bei` → `von`. Origin = `aus`, just left = `von`."),
      ("zu oder in?", "`zum Kino` = over to it · `ins Kino` = in to watch. `zur Schule gehen` = be a pupil. `zu` + Dat is never wrong for a building."),
      ("!gehen = zu Fuß", "wheels → `fahren`, wings → `fliegen`; vehicle = `mit dem Bus/Zug/Auto`, walking = `zu Fuß`; inside: `im Bus`, `auf dem Fahrrad`"),
      ("Gesprochen", "`**Wo** gehst du **hin**?` = wohin · `**Wo** kommst du **her**?` = woher")),
  ),
  B("ref-laender", "Städte, Länder & Inseln", "A1", "nach Italien · in die Türkei · auf Mallorca",
    T("", ["Typ", "Wohin?", "Wo?", "Woher?"], [
      ["ohne Artikel", "nach Deutschland", "in Deutschland", "aus Deutschland"],
      ["{m:der} Iran", "in den Iran", "im Iran", "aus dem Iran"],
      ["{f:die} Schweiz", "in die Schweiz", "in der Schweiz", "aus der Schweiz"],
      ["{p:die} USA", "in die USA", "in den USA", "aus den USA"],
      ["Stadt", "nach Lahore", "in Lahore", "aus Lahore"],
      ["Insel", "nach Mallorca", "auf Mallorca", "von Mallorca"],
    ]),
    T("Länder mit Artikel", ["Artikel", "Länder", "wohin · wo · woher"], [
      ["{m:der}", "Iran · Irak · Libanon · Sudan · Jemen · Kongo · Tschad · Vatikan", "in den · im · aus dem"],
      ["{f:die}", "Schweiz · Türkei · Ukraine · Slowakei · Mongolei · Dominikanische Republik", "in die · in der · aus der"],
      ["{p:die (Pl)}", "USA · Niederlande · Philippinen · Malediven · Vereinigte Arabische Emirate", "in die · in den · aus den"],
    ], full=True),
    T("Straßen, Plätze, Landschaften", ["Ort", "Präposition"], [
      ["Straße (Adresse)", "in der Bahnhofstraße · aber: auf der Straße spielen"],
      ["Platz · Ecke · Fluss · Küste", "am Marienplatz · an der Ecke · am Fluss · an der Ostsee"],
      ["Wald · Gebirge · Park", "im Schwarzwald · in den Alpen · im Park"],
      ["Land / Stadt", "auf dem Land · in der Stadt"],
      ["Richtung", "nach links · rechts · Norden · oben · unten · draußen"],
    ]),
    N(("!-ei = feminin", "`die Türk**ei**, Slowak**ei**, Mongol**ei**` → `in die`, never nach"),
      ("Inseln", "travel `nach`, be `auf`: `Wir fliegen **nach** Mallorca. Wir sind **auf** Mallorca.`"),
      ("!Herkunft = aus", "`Ich komme **aus** Pakistan, **aus** Lahore.` — `von` = just came back from")),
  ),
  B("ref-verschmelzung", "Verschmelzungen", "A1", "im vs ins · zum vs zur",
    T("", ["Kurz", "=", "Kasus", "Beispiel"], [
      ["im", "in dem", "{dat:Dativ}", "im Büro · im Juli · im Bett liegen"],
      ["ins", "in das", "{akk:Akkusativ}", "ins Büro · ins Kino · ins Bett gehen"],
      ["am", "an dem", "{dat:Dativ}", "am Fenster · am Montag · am besten"],
      ["ans", "an das", "{akk:Akkusativ}", "ans Fenster · ans Meer"],
      ["beim", "bei dem", "{dat:Dativ}", "beim Arzt · beim Essen"],
      ["vom", "von dem", "{dat:Dativ}", "vom Bahnhof · vom Arzt"],
      ["zum", "zu dem", "{dat:Dativ}", "zum Arzt · zum Beispiel"],
      ["zur", "zu der", "{dat:Dativ}", "zur Schule · zur Arbeit"],
      ["aufs", "auf das", "{akk:Akkusativ}", "aufs Sofa · aufs Land"],
      ["fürs", "für das", "{akk:Akkusativ}", "fürs Auto"],
      ["durchs", "durch das", "{akk:Akkusativ}", "durchs Fenster"],
      ["ums", "um das", "{akk:Akkusativ}", "ums Haus · ums Leben"],
    ]),
    N(("im / ins", "`im` = Wo? (`Ich bin im Kino`) · `ins` = Wohin? (`Ich gehe ins Kino`)"),
      ("!Nur dem & das", "only these fuse — plus `zu der → zur`: `zur Arbeit` but `in der Arbeit`"),
      ("Nicht verschmelzen", "article is pointing / relative clause follows: `**in dem** Haus, in dem ich geboren bin`"),
      ("Muss verschmelzen", "`zum Beispiel · zum Glück · im Moment · am Anfang · am Ende · am besten · am Montag · im Mai · beim Frühstück · zum Schwimmen`"),
      ("!Register", "`am ans im ins beim vom zum zur` everywhere · `aufs durchs fürs ums` normal writing · `vorm hinterm überm unterm aufm` spoken only")),
  ),
  B("ref-genitivpraep", "Genitivpräpositionen", "B1", "wegen · trotz · während",
    T("", ["Präp.", "Bedeutung", "Beispiel"], [
      ["wegen", "because of", "**wegen des** Wetters · **wegen der** Arbeit"],
      ["trotz", "despite", "**trotz des** Regens"],
      ["während", "during", "**während der** Woche · **während des** Kurses"],
      ["(an)statt", "instead of", "**statt des** Autos"],
      ["außerhalb / innerhalb", "outside / within", "**innerhalb einer** Woche · **außerhalb der** Stadt"],
      ["aufgrund", "due to", "**aufgrund der** Verspätung"],
      ["anstelle", "in place of", "**anstelle des** Chefs"],
    ]),
    N(("Genitiv bilden", "m/n noun + `-(e)s`: `des Autos, des Mannes` · f/pl: only the article changes"),
      ("!Gesprochen: Dativ", "`wegen dem Wetter` is everyday speech; write the genitive"),
      ("von + Dativ", "written `das Auto meines Bruders` · spoken `das Auto von meinem Bruder` · names: `Annas Hund` (no apostrophe)")),
  ),
]))

# ─────────────────────────── Zahlen & Zeit
SECTIONS.append(("sec-zahlen", "Zahlen & Zeit", [
  B("ref-zahlen", "Zahlen, Uhrzeit & Datum", "A1", "halb zwei = 13:30 · der dritte",
    T("Zahlen", ["0–10", "11–20", "Zehner", "groß"], [
      ["0 null · 1 eins · 2 zwei", "11 elf · 12 zwölf", "20 zwanzig", "100 (ein)hundert"],
      ["3 drei · 4 vier · 5 fünf", "13 dreizehn · 14 vierzehn", "30 drei**ß**ig", "1 000 (ein)tausend"],
      ["6 sechs · 7 sieben", "15 fünfzehn · 16 **sech**zehn", "40 vierzig · 50 fünfzig", "1 000 000 eine Million"],
      ["8 acht · 9 neun · 10 zehn", "17 **sieb**zehn · 18 · 19", "60 **sech**zig · 70 **sieb**zig · 80 · 90", "1996 neunzehnhundertsechsundneunzig"],
    ], rh=False, full=True),
    T("Uhrzeit (inoffiziell)", ["Uhr", "man sagt", "Uhr", "man sagt"], [
      ["13:00", "ein Uhr / eins", "13:30", "**halb zwei**"],
      ["13:05", "fünf nach eins", "13:35", "fünf nach halb zwei"],
      ["13:10", "zehn nach eins", "13:40", "zwanzig vor zwei"],
      ["13:15", "Viertel nach eins", "13:45", "Viertel vor zwei"],
      ["13:20", "zwanzig nach eins", "13:50", "zehn vor zwei"],
      ["13:25", "fünf vor halb zwei", "13:55", "fünf vor zwei"],
    ], rh=False),
    T("Ordinalzahlen", ["Regel", "Bildung", "Beispiele"], [
      ["1.–19.", "+ -te", "der zwei**te**, vier**te**, zehn**te**"],
      ["ab 20.", "+ -ste", "der zwanzig**ste**, einunddreißig**ste**"],
      ["unregelmäßig", "—", "**erste** · **dritte** · **siebte** · **achte**"],
    ]),
    T("Fragen", ["Frage", "Antwort"], [
      ["Wie spät ist es? / Wie viel Uhr ist es?", "Es ist halb acht."],
      ["Um wie viel Uhr?", "**Um** halb acht."],
      ["Der Wievielte ist heute?", "Heute ist **der** 6. September. (sechs**te**)"],
      ["Wann hast du Geburtstag?", "**Am** 6. September. (sechs**ten**)"],
    ]),
    T("Tage, Monate, Jahreszeiten — alle {m:der}", ["", "Wörter"], [
      ["Tage", "Montag · Dienstag · Mittwoch · Donnerstag · Freitag · Samstag · Sonntag"],
      ["Monate", "Januar · Februar · März · April · Mai · Juni · Juli · August · September · Oktober · November · Dezember"],
      ["Jahreszeiten", "Frühling · Sommer · Herbst · Winter"],
    ], full=True),
    N(("Regel", "units before tens, one word: `47 = **sieben**und**vierzig**` · `eins → ein` before a noun: `ein Kaffee, einundzwanzig`"),
      ("Offiziell", "24h, read digits: `13:45 → dreizehn Uhr fünfundvierzig`"),
      ("!halb", "`halb zwei` = **13:30** — counts towards the next hour")),
  ),
  B("ref-zeit", "Zeitangaben", "A1", "um · am · im · seit · vor · in",
    T("", ["Präp.", "wofür", "Beispiel"], [
      ["um", "Uhrzeit", "um 8 Uhr, um halb neun"],
      ["am", "Tage, Datum, Tageszeiten", "am Montag, am 6. September, am Morgen, am Wochenende"],
      ["im", "Monate, Jahreszeiten, Jahr", "im Juli, im Winter, im Jahr 2026"],
      ["in der", "Nacht (Ausnahme)", "in der Nacht"],
      ["von … bis", "Zeitraum", "von 9 bis 17 Uhr, von Montag bis Freitag"],
      ["seit + Dat", "begann früher, dauert an → Präsens", "Ich lerne **seit** einem Jahr Deutsch."],
      ["vor + Dat", "vorbei → Vergangenheit", "Ich habe **vor** einem Jahr angefangen."],
      ["in + Dat", "ab jetzt gerechnet → Zukunft", "Ich fahre **in** einem Jahr zurück."],
      ["ab + Dat", "von da an", "ab Montag, ab nächster Woche"],
      ["für + Akk", "geplante Dauer", "für zwei Wochen nach Hause fahren"],
      ["—", "Adverbien, Akk-Dauer", "heute, morgen, gestern, nächste Woche, letztes Jahr, jeden Tag"],
    ], full=True),
    T("Tageszeiten", ["Wörter"], [
      ["der Morgen · Vormittag · Mittag · Nachmittag · Abend · {f:die Nacht}"],
      ["heute Morgen · gestern Abend · morgen früh (nicht morgen Morgen)"],
    ], rh=False),
  ),
]))

# ─────────────────────────── Stolperfallen
WIRES = [
  ("A1", "Ich habe nach Hause gegangen.", "Ich **bin** nach Hause gegangen.", "movement A → B takes sein"),
  ("A1", "Ich helfe dich.", "Ich helfe **dir**.", "helfen is a Dativ verb (also danken, gefallen, gehören, antworten)"),
  ("A1", "Morgen ich muss arbeiten.", "Morgen **muss ich** arbeiten.", "verb stays on Pos 2; subject goes behind it"),
  ("A1", "Ich kann sprechen Deutsch.", "Ich kann Deutsch **sprechen**.", "infinitive closes the bracket"),
  ("A1", "Ich fahre mit der Bus.", "Ich fahre mit **dem** Bus.", "mit = Dativ; der Bus → dem"),
  ("A1", "Ich habe nicht Zeit.", "Ich habe **keine** Zeit.", "bare noun → kein"),
  ("A1", "Ich habe gestern telefoniert mit ihm.", "Ich habe gestern mit ihm **telefoniert**.", "participle is the last word"),
  ("A1", "Er sprecht sehr schnell.", "Er **spricht** sehr schnell.", "e → i for du and er/sie/es"),
  ("A1", "Ich habe seit zwei Jahren hier gewohnt.", "Ich **wohne** seit zwei Jahren hier.", "still ongoing → Präsens"),
  ("A1", "halb zwei = 14:30", "halb zwei = **13:30**", "halb + next hour"),
  ("A1", "Ich gehe nach Kino.", "Ich gehe **ins** Kino.", "nach only for cities, countries, directions, Hause"),
  ("A1", "Ich bin ins Büro.", "Ich bin **im** Büro.", "sein = position → im (Dativ)"),
  ("A1", "Ich gehe zu Hause.", "Ich gehe **nach** Hause.", "nach Hause = trip · zu Hause = place"),
  ("A1", "Ich fahre nach die Schweiz.", "Ich fahre **in** die Schweiz.", "country with article → in + Akk"),
  ("A1", "Ich gehe nach Berlin.", "Ich **fahre** nach Berlin.", "gehen = on foot"),
  ("A1", "Ich komme von Pakistan.", "Ich komme **aus** Pakistan.", "origin = aus"),
  ("A1", "Ich spiele mit den Kinder.", "Ich spiele mit den Kinder**n**.", "Dativ Plural noun -n"),
  ("A1", "das Auto des Mann", "das Auto des Mann**es**", "Gen m/n noun -(e)s"),
  ("A2", "Ich bin größer wie du.", "Ich bin größer **als** du.", "difference → als"),
  ("A2", "Ich muss nicht rauchen. (= mustn't)", "Ich **darf** nicht rauchen.", "mustn't = nicht dürfen"),
  ("A2", "…, weil ich bin müde.", "…, weil ich müde **bin**.", "weil → verb to the end (or use denn)"),
  ("A2", "Wenn ich klein war, …", "**Als** ich klein war, …", "one past event → als"),
  ("A2", "Ein guten Wein.", "Ein gut**er** Wein.", "ein is silent in m Nom → adjective -er"),
  ("A2", "Ich freue mich auf dir.", "Ich freue mich auf **dich**.", "sich freuen auf + Akk"),
  ("A2", "Ich habe mein Auto reparieren gelassen.", "… reparieren **lassen**.", "double infinitive"),
  ("A2", "Ich habe viele guten Freunde.", "Ich habe viele gut**e** Freunde.", "viele signals nothing → -e"),
  ("B1", "Das Haus ist gebaut geworden.", "Das Haus ist gebaut **worden**.", "passive perfect: worden"),
  ("B1", "Ich warte darauf meinen Chef.", "Ich warte **auf** meinen Chef.", "da-words replace things, not people"),
  ("B1", "Ich kenne den Student.", "Ich kenne den Student**en**.", "N-Deklination"),
]
